
import React, { useState, useEffect, useMemo } from 'react';
import { collection, onSnapshot, doc, updateDoc, addDoc, setDoc, query, where, getDocs, increment, Timestamp, orderBy, limit } from 'firebase/firestore';
import { db } from '../../services/firebase';
import { VillageType, HarvestLog, FinancialRecord } from '../../types';

interface FirestoreResource {
    id: string;
    materialId?: string; // Autogenerated readable ID
    name: string;
    quantity: number;
    unit: string;
    category: string;
    lowStockThreshold: number;
    unitCost: number; // Cost per 1 unit (RM), except for 'L' which is per 10 units
    updatedAt: any;
    // Equipment specific fields
    condition?: 'Excellent' | 'Good' | 'Fair' | 'Service Due';
    location?: string; // Comma separated list of rooms
    lastServiceDate?: string;
    operationStatus?: string; // Manual override status
}

interface InventoryItem {
    id: string;
    name: string;
    quantity: number;
    unit: string;
    status: 'Ready' | 'Hold';
    batchId?: string;
    updatedAt: any;
}

interface ResourcesTabProps {
    villageId: VillageType;
    userEmail: string;
    theme?: any;
    onSuccess?: (msg: string) => void;
    financialRecords: FinancialRecord[];
    initialPurchaseState?: { active: boolean, itemId?: string };
    onResetPurchaseState?: () => void;
}

// Requirements per 1kg of Mushroom Yield (Based on FarmingTab recipes)
const MATERIAL_REQUIREMENTS: Record<string, number> = {
    "MAT-573260995": 20,   // Straw (20kg per 1kg yield)
    "MAT-545594408": 75,   // Water (50+5+20 = 75L per 1kg yield)
    "MAT-406637503": 0.5,  // Bran (0.5kg per 1kg yield)
    "MAT-446059102": 0.2,  // Gypsum (0.2kg per 1kg yield)
    "MAT-282015830": 1,    // Spawn (1kg per 1kg yield)
};

export const ResourcesTab: React.FC<ResourcesTabProps> = ({ 
    villageId, userEmail, theme, onSuccess, financialRecords, initialPurchaseState, onResetPurchaseState 
}) => {
    // --- State ---
    const [resources, setResources] = useState<FirestoreResource[]>([]);
    const [inventory, setInventory] = useState<InventoryItem[]>([]);
    const [harvestLogs, setHarvestLogs] = useState<HarvestLog[]>([]); 
    const [loading, setLoading] = useState(true);
    
    // Environment Context for Equipment Status
    const [latestEnvLog, setLatestEnvLog] = useState<{temperature: number, humidity: number} | null>(null);

    // Aggregation states for Village C
    const [harvestLogsA, setHarvestLogsA] = useState<HarvestLog[]>([]);
    const [harvestLogsB, setHarvestLogsB] = useState<HarvestLog[]>([]);
    const [finRecordsA, setFinRecordsA] = useState<FinancialRecord[]>([]);
    const [finRecordsB, setFinRecordsB] = useState<FinancialRecord[]>([]);

    // KPIs
    const [todayProduction, setTodayProduction] = useState(0);
    const [inventoryOutCount, setInventoryOutCount] = useState(0); 

    // Stock Transaction Modal State
    const [isTransModalOpen, setIsTransModalOpen] = useState(false);
    const [transType, setTransType] = useState<'IN' | 'OUT'>('IN');
    const [selectedItem, setSelectedItem] = useState<FirestoreResource | null>(null);
    const [transQty, setTransQty] = useState('');
    const [transReason, setTransReason] = useState('');

    // Add New Material Modal State
    const [isAddMatModalOpen, setIsAddMatModalOpen] = useState(false);
    const [newMatName, setNewMatName] = useState('');
    const [newMatCategory, setNewMatCategory] = useState('Input');
    const [newMatUnit, setNewMatUnit] = useState('kg');
    const [newMatQty, setNewMatQty] = useState('');
    const [newMatThreshold, setNewMatThreshold] = useState('');
    const [newMatUnitCost, setNewMatUnitCost] = useState('');

    // Edit Material Modal State
    const [isEditMatModalOpen, setIsEditMatModalOpen] = useState(false);
    const [editItemId, setEditItemId] = useState('');
    const [editItemName, setEditItemName] = useState('');
    const [editItemUnitCost, setEditItemUnitCost] = useState('');
    const [editItemCategory, setEditItemCategory] = useState('Input');
    const [editItemUnit, setEditItemUnit] = useState('kg');
    const [isUpdatingDetails, setIsUpdatingDetails] = useState(false);

    // Purchase Request Modal State
    const [isPurchaseModalOpen, setIsPurchaseModalOpen] = useState(false);
    const [purchaseItemId, setPurchaseItemId] = useState(''); 
    const [purchaseQty, setPurchaseQty] = useState('');
    const [purchaseCost, setPurchaseCost] = useState('');
    const [purchaseNotes, setPurchaseNotes] = useState('');

    // Confirm Receipt Logic
    const [isConfirmingReceipt, setIsConfirmingReceipt] = useState<string | null>(null);
    const [receivedInputs, setReceivedInputs] = useState<Record<string, string>>({});
    const [showSupplyHistory, setShowSupplyHistory] = useState(false);

    // Notifications State
    const [activeNotification, setActiveNotification] = useState<{title: string, message: string} | null>(null);

    // --- History Drawer State ---
    const [isHistoryDrawerOpen, setIsHistoryDrawerOpen] = useState(false);
    const [historyLogs, setHistoryLogs] = useState<any[]>([]);
    const [historyMaterial, setHistoryMaterial] = useState<FirestoreResource | null>(null);
    const [loadingHistory, setLoadingHistory] = useState(false);

    // --- Helpers ---
    const getResourceColName = (vid: VillageType) => vid === VillageType.A ? 'resourcesA' : vid === VillageType.B ? 'resourcesB' : 'resourcesC';
    const getInventoryColName = (vid: VillageType) => vid === VillageType.A ? 'inventoryA' : vid === VillageType.B ? 'inventoryB' : 'inventoryC';
    const getHarvestColName = (vid: VillageType) => vid === VillageType.A ? 'harvestYield_A' : vid === VillageType.B ? 'harvestYield_B' : 'harvestYield_A';
    
    const getFinancialCollectionName = (vid: VillageType) => {
        if (vid === VillageType.A) return "financialRecords_A";
        if (vid === VillageType.B) return "financialRecords_B";
        if (vid === VillageType.C) return "financialRecords_C";
        return "financialRecords"; 
    };

    const handleViewHistory = async (item: FirestoreResource) => {
        setHistoryMaterial(item);
        setIsHistoryDrawerOpen(true);
        setLoadingHistory(true);
        setHistoryLogs([]);
        try {
            const colName = getResourceColName(villageId);
            const q = query(
                collection(db, colName, item.id, "stock_history"),
                orderBy("timestamp", "desc"),
                limit(50) // Increased limit to see more history
            );
            const snap = await getDocs(q);
            const logs = snap.docs.map(d => ({id: d.id, ...d.data()}));
            setHistoryLogs(logs);
        } catch(e) {
            console.error("Error fetching history", e);
        } finally {
            setLoadingHistory(false);
        }
    };

    // --- Auto Set Thresholds Logic ---
    const handleAutoSetThresholds = async () => {
        const TARGET_YIELD_KG = 30;
        const collectionName = getResourceColName(villageId);
        let updatedCount = 0;

        try {
            await Promise.all(resources.map(async (res) => {
                const reqPerKg = MATERIAL_REQUIREMENTS[res.id];
                if (reqPerKg !== undefined) {
                    const newThreshold = reqPerKg * TARGET_YIELD_KG;
                    if (res.lowStockThreshold < newThreshold) {
                        const resRef = doc(db, collectionName, res.id);
                        await updateDoc(resRef, {
                            lowStockThreshold: newThreshold,
                            updatedAt: new Date().toISOString()
                        });
                        updatedCount++;
                    }
                }
            }));
            
            if (updatedCount > 0) {
                if (onSuccess) onSuccess(`Safety limits updated for ${updatedCount} items (Target: 30kg yield).`);
            } else {
                if (onSuccess) onSuccess("Stock limits already compliant with 30kg yield capacity.");
            }
        } catch (e) {
            console.error("Auto-set thresholds failed", e);
            alert("Failed to update thresholds.");
        }
    };

    // --- Auto Purchase Trigger Effect ---
    useEffect(() => {
        if (initialPurchaseState?.active) {
            setIsPurchaseModalOpen(true);
            if (initialPurchaseState.itemId) {
                setPurchaseItemId(initialPurchaseState.itemId);
            }
            if (onResetPurchaseState) onResetPurchaseState();
        }
    }, [initialPurchaseState]);

    // --- Purchase Calculation Logic ---
    const selectedPurchaseResource = useMemo(() => 
        resources.find(r => r.id === purchaseItemId), 
    [purchaseItemId, resources]);

    useEffect(() => {
        if (selectedPurchaseResource && purchaseQty) {
            const qty = parseFloat(purchaseQty);
            if (!isNaN(qty) && qty > 0) {
                const factor = selectedPurchaseResource.unit === 'L' ? 10 : 1;
                const estimatedTotal = ((qty / factor) * (selectedPurchaseResource.unitCost || 0)).toFixed(2);
                setPurchaseCost(estimatedTotal);
            } else if (purchaseQty === '') {
                setPurchaseCost('');
            }
        }
    }, [selectedPurchaseResource, purchaseQty]);

    // --- Aggregation Logic: Unified Supply Chain View for Village C ---
    const activeHarvestSource = useMemo(() => {
        if (villageId === VillageType.C) {
            return [...harvestLogsA, ...harvestLogsB];
        }
        return harvestLogs;
    }, [villageId, harvestLogs, harvestLogsA, harvestLogsB]);

    const activeFinSource = useMemo(() => {
        if (villageId === VillageType.C) {
            return [...financialRecords, ...finRecordsA, ...finRecordsB];
        }
        return financialRecords;
    }, [villageId, financialRecords, finRecordsA, finRecordsB]);

    // Track pending deliveries from financial records
    const pendingReceipts = useMemo(() => {
        return activeFinSource.filter(rec => 
            rec.category === 'Supplies' && 
            rec.type === 'EXPENSE' && 
            rec.status === 'COMPLETED' && 
            rec.receivedInStock === false &&
            rec.materialId // Must have a linked material
        );
    }, [activeFinSource]);

    // Track receipts with discrepancies
    const discrepancyReceipts = useMemo(() => {
        return activeFinSource.filter(rec => {
            const hasVariance = rec.orderQty !== undefined && rec.actualReceivedQty !== undefined && rec.orderQty !== rec.actualReceivedQty;
            const notResolved = !(rec as any).varianceResolved;
            return rec.category === 'Supplies' && rec.receivedInStock === true && hasVariance && notResolved;
        });
    }, [activeFinSource]);

    // History of received supplies
    const receivedSuppliesHistory = useMemo(() => {
        return activeFinSource.filter(rec => 
            rec.category === 'Supplies' && 
            rec.type === 'EXPENSE' && 
            rec.receivedInStock === true &&
            rec.materialId
        ).sort((a,b) => (b.updatedAt || b.date).localeCompare(a.updatedAt || a.date)).slice(0, 10);
    }, [activeFinSource]);

    // Map pending weights to resource ID for the "Pending Received" column
    const pendingWeightsByResource = useMemo(() => {
        const mapping: Record<string, number> = {};
        pendingReceipts.forEach(rec => {
            if (rec.materialId) {
                // Use orderQty if available, else extract from description
                const qty = rec.orderQty || (() => {
                    const match = rec.description?.match(/Purchase Request: ([\d.]+) /);
                    return match ? parseFloat(match[1]) : 0;
                })();
                mapping[rec.materialId] = (mapping[rec.materialId] || 0) + qty;
            }
        });
        return mapping;
    }, [pendingReceipts]);

    // --- Core Logic: Inventory Calculation ---
    const processedOutputInventory = useMemo(() => {
        const harvestTotals: Record<string, { batchId: string, strain: string, totalHarvest: number, lastTimestamp: string }> = {};
        
        activeHarvestSource.forEach(log => {
            const batchId = log.batchId;
            const weight = log.weightKg || log.totalYield || 0;
            if (!harvestTotals[batchId]) {
                harvestTotals[batchId] = { 
                    batchId, 
                    strain: log.strain, 
                    totalHarvest: 0, 
                    lastTimestamp: log.timestamp 
                };
            }
            harvestTotals[batchId].totalHarvest += weight;
            if (new Date(log.timestamp) > new Date(harvestTotals[batchId].lastTimestamp)) {
                harvestTotals[batchId].lastTimestamp = log.timestamp;
            }
        });

        const salesTotals: Record<string, number> = {};
        activeFinSource.forEach(rec => {
            if (rec.category === 'Sales' && rec.batchId && rec.weightKg && rec.type === 'INCOME') {
                salesTotals[rec.batchId] = (salesTotals[rec.batchId] || 0) + rec.weightKg;
            }
        });

        return Object.values(harvestTotals).map(item => {
            const sold = salesTotals[item.batchId] || 0;
            const remaining = Math.max(0, item.totalHarvest - sold);
            return {
                ...item,
                soldWeight: sold,
                remainingWeight: remaining
            };
        }).sort((a, b) => new Date(b.lastTimestamp).getTime() - new Date(a.lastTimestamp).getTime());
    }, [activeHarvestSource, activeFinSource]);

    const totalCurrentStock = useMemo(() => {
        return processedOutputInventory.reduce((acc, curr) => acc + curr.remainingWeight, 0);
    }, [processedOutputInventory]);

    const totalResourceValue = useMemo(() => {
        return resources.reduce((acc, curr) => {
            const factor = curr.unit === 'L' ? 10 : 1;
            return acc + ((curr.quantity || 0) / factor * (curr.unitCost || 0));
        }, 0);
    }, [resources]);

    // --- New Action-Oriented KPI Logic ---
    const yieldStats = useMemo(() => {
        const total = processedOutputInventory.reduce((a, c) => a + c.totalHarvest, 0);
        if (processedOutputInventory.length < 2) return { total, change: 0 };
        const latest = processedOutputInventory[0].totalHarvest;
        const previous = processedOutputInventory[1].totalHarvest;
        const change = previous > 0 ? ((latest - previous) / previous) * 100 : 0;
        return { total, change };
    }, [processedOutputInventory]);

    const salesRevenue = useMemo(() => {
        const totalWeight = processedOutputInventory.reduce((a, c) => a + c.soldWeight, 0);
        const revenue = activeFinSource
            .filter(rec => rec.category === 'Sales' && rec.type === 'INCOME' && rec.status === 'COMPLETED')
            .reduce((acc, curr) => acc + curr.amount, 0);
        return { totalWeight, revenue };
    }, [processedOutputInventory, activeFinSource]);

    const supplyDays = useMemo(() => {
        const sevenDaysAgo = new Date();
        sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);
        const recentSales = activeFinSource.filter(rec => 
            rec.category === 'Sales' && 
            rec.type === 'INCOME' && 
            new Date(rec.date) >= sevenDaysAgo
        );
        const weeklyWeight = recentSales.reduce((acc, curr) => acc + (curr.weightKg || 0), 0);
        const dailyBurnRate = weeklyWeight / 7;
        const days = dailyBurnRate > 0 ? totalCurrentStock / dailyBurnRate : 0;
        return days;
    }, [activeFinSource, totalCurrentStock]);

    const resourceAtRisk = useMemo(() => {
        return resources.reduce((acc, curr) => {
            if (curr.quantity <= curr.lowStockThreshold) {
                const factor = curr.unit === 'L' ? 10 : 1;
                return acc + ((curr.quantity || 0) / factor * (curr.unitCost || 0));
            }
            return acc;
        }, 0);
    }, [resources]);

    // --- Data Fetching ---
    useEffect(() => {
        const resCol = collection(db, getResourceColName(villageId));
        const invCol = collection(db, getInventoryColName(villageId));

        const unsubRes = onSnapshot(resCol, (snapshot) => {
            const list: FirestoreResource[] = [];
            snapshot.forEach(doc => list.push({ id: doc.id, ...doc.data() } as FirestoreResource));
            
            // Check if equipment needs seeding (auto-generate requirement)
            const hasEquipment = list.some(i => i.category === 'Equipment');
            if (!hasEquipment && list.length > 0 && villageId !== VillageType.C) {
                seedDefaultResources(list);
            } else if (list.length === 0 && villageId !== VillageType.C) {
                seedDefaultResources([]);
            } else {
                setResources(list);
            }
            setLoading(false);
        });

        const unsubInv = onSnapshot(invCol, (snapshot) => {
             const list: InventoryItem[] = [];
             snapshot.forEach(doc => list.push({ id: doc.id, ...doc.data() } as InventoryItem));
             setInventory(list);
        });

        // Harvest logic based on village
        if (villageId === VillageType.C) {
            // Aggregated view for C
            const unsubA = onSnapshot(query(collection(db, 'harvestYield_A'), orderBy('timestamp', 'desc'), limit(150)), (snap) => {
                setHarvestLogsA(snap.docs.map(d => ({id: d.id, ...d.data()} as HarvestLog)));
            });
            const unsubB = onSnapshot(query(collection(db, 'harvestYield_B'), orderBy('timestamp', 'desc'), limit(150)), (snap) => {
                setHarvestLogsB(snap.docs.map(d => ({id: d.id, ...d.data()} as HarvestLog)));
            });
            const unsubFinA = onSnapshot(query(collection(db, 'financialRecords_A'), where('category', '==', 'Sales')), (snap) => {
                setFinRecordsA(snap.docs.map(d => ({id: d.id, ...d.data()} as FinancialRecord)));
            });
            const unsubFinB = onSnapshot(query(collection(db, 'financialRecords_B'), where('category', '==', 'Sales')), (snap) => {
                setFinRecordsB(snap.docs.map(d => ({id: d.id, ...d.data()} as FinancialRecord)));
            });

            return () => { unsubRes(); unsubInv(); unsubA(); unsubB(); unsubFinA(); unsubFinB(); };
        } else {
            const harvCol = collection(db, getHarvestColName(villageId));
            const qHarvest = query(harvCol, orderBy('timestamp', 'desc'), limit(150));
            const unsubHarvest = onSnapshot(qHarvest, (snapshot) => {
                const list: HarvestLog[] = [];
                snapshot.forEach(doc => list.push({ id: doc.id, ...doc.data() } as HarvestLog));
                setHarvestLogs(list);
            });

            // Fetch Environment snapshot for Equipment Status
            const envColName = `environmentLogs_${villageId.replace(/\s/g, '')}`;
            const qEnv = query(collection(db, envColName), orderBy('timestamp', 'desc'), limit(1));
            const unsubEnv = onSnapshot(qEnv, (snap) => {
                if (!snap.empty) {
                    const d = snap.docs[0].data();
                    setLatestEnvLog({ temperature: d.temperature, humidity: d.humidity });
                }
            });

            return () => { unsubRes(); unsubInv(); unsubHarvest(); unsubEnv(); };
        }
    }, [villageId]);

    useEffect(() => {
        fetchKPIs();
    }, [villageId]);

    const fetchKPIs = async () => {
        try {
            if (villageId === VillageType.C) {
                setTodayProduction(0); 
                setInventoryOutCount(0);
                return;
            }
            const harvestColName = getHarvestColName(villageId);
            const harvestCol = collection(db, harvestColName);
            const startOfDay = new Date();
            startOfDay.setHours(0,0,0,0);
            const qToday = query(harvestCol, where('timestamp', '>=', startOfDay.toISOString()));
            const snapToday = await getDocs(qToday);
            let todayTotal = 0;
            snapToday.forEach(doc => todayTotal += (doc.data().totalYield || doc.data().weightKg || 0));
            setTodayProduction(todayTotal);

            const finColName = getFinancialCollectionName(villageId);
            const finCol = collection(db, finColName);
            const qSales = query(finCol, where('villageId', '==', villageId), where('type', '==', 'INCOME'), where('category', '==', 'Sales'));
            const snapSales = await getDocs(qSales);
            setInventoryOutCount(snapSales.size);
        } catch (e) {
            console.error("Error fetching KPIs", e);
        }
    };

    const seedDefaultResources = async (existingList: FirestoreResource[] = []) => {
        const materialDefaults = [
            { name: "Straw (Substrate)", quantity: 1000, unit: "kg", category: "Input", lowStockThreshold: 200, unitCost: 1.50, materialId: "MAT-573260995" },
            { name: "Spawn (Inoculum)", quantity: 100, unit: "kg", category: "Input", lowStockThreshold: 20, unitCost: 12.00, materialId: "MAT-282015830" },
            { name: "Bran", quantity: 400, unit: "kg", category: "Nutrient", lowStockThreshold: 100, unitCost: 3.50, materialId: "MAT-406637503" },
            { name: "Gypsum (Conditioner)", quantity: 50, unit: "kg", category: "Nutrient", lowStockThreshold: 10, unitCost: 2.00, materialId: "MAT-446059102" },
            { name: "Water Supply Tank", quantity: 5000, unit: "L", category: "Utility", lowStockThreshold: 1000, unitCost: 0.50, materialId: "MAT-545594408" },
        ];

        const equipmentDefaults = [
            { name: "Exhaust Fan", quantity: 4, unit: "units", category: "Equipment", lowStockThreshold: 1, unitCost: 350.00, materialId: "EQP-FAN-001", location: "", condition: "Good" },
            { name: "Humidifier", quantity: 2, unit: "units", category: "Equipment", lowStockThreshold: 1, unitCost: 800.00, materialId: "EQP-HUM-001", location: "", condition: "Excellent" },
            { name: "Heater", quantity: 3, unit: "units", category: "Equipment", lowStockThreshold: 1, unitCost: 120.00, materialId: "EQP-HEAT-001", location: "", condition: "Fair" },
            { name: "Air Cooler", quantity: 1, unit: "system", category: "Equipment", lowStockThreshold: 0, unitCost: 1500.00, materialId: "EQP-COOL-001", location: "", condition: "Good" },
        ];

        const defaults = [...materialDefaults, ...equipmentDefaults];
        const col = collection(db, getResourceColName(villageId));
        
        for (const item of defaults) {
            if (!existingList.some(r => r.name === item.name)) {
                await setDoc(doc(col, item.materialId), { ...item, updatedAt: new Date().toISOString() });
            }
        }
    };

    const handleTransaction = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!selectedItem || !transQty) return;
        const qty = parseFloat(transQty);
        if (isNaN(qty) || qty <= 0) return;
        
        const collectionName = getResourceColName(villageId);
        const itemRef = doc(db, collectionName, selectedItem.id);
        
        const adjustment = transType === 'IN' ? qty : -qty;
        const newQuantity = (selectedItem.quantity || 0) + adjustment;

        if (transType === 'OUT' && newQuantity < 0) {
            alert("Insufficient stock!");
            return;
        }

        try {
            await updateDoc(itemRef, {
                quantity: newQuantity,
                updatedAt: new Date().toISOString()
            });

            await addDoc(collection(db, collectionName, selectedItem.id, "stock_history"), {
                type: transType, 
                quantity: qty,
                reason: transReason || (transType === 'IN' ? 'Restock' : 'Usage'),
                user: userEmail,
                timestamp: new Date().toISOString()
            });

            setIsTransModalOpen(false);
            setTransQty('');
            setTransReason('');
            setSelectedItem(null);
            if (onSuccess) onSuccess(`Stock ${transType === 'IN' ? 'added' : 'deducted'} successfully.`);
        } catch (e) {
            console.error("Transaction failed", e);
            alert("Failed to update stock.");
        }
    };
    
    const handleAddMaterial = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!newMatName || !newMatQty) return;
        try {
            const collectionName = getResourceColName(villageId);
            const initialQty = parseFloat(newMatQty) || 0;
            const threshold = parseFloat(newMatThreshold) || 0;
            const unitCost = parseFloat(newMatUnitCost) || 0;
            const materialId = "MAT-" + Date.now().toString().slice(-6) + Math.floor(100 + Math.random() * 900);
            await setDoc(doc(db, collectionName, materialId), {
                materialId,
                name: newMatName,
                category: newMatCategory,
                unit: newMatUnit,
                quantity: initialQty,
                lowStockThreshold: threshold,
                unitCost: unitCost,
                updatedAt: new Date().toISOString()
            });
            if (initialQty > 0) {
                await addDoc(collection(db, collectionName, materialId, "stock_history"), {
                    type: 'IN', quantity: initialQty, reason: 'Initial Stock', user: userEmail, timestamp: new Date().toISOString()
                });
            }
            if (onSuccess) onSuccess(`Added ${newMatName} (ID: ${materialId})`);
            setIsAddMatModalOpen(false);
            setNewMatName(''); setNewMatCategory('Input'); setNewMatUnit('kg'); setNewMatQty(''); setNewMatThreshold(''); setNewMatUnitCost('');
        } catch (e) {
            console.error("Add Material failed", e);
            alert("Failed to add material.");
        }
    };

    const handleUpdateDetails = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!editItemId || !editItemUnitCost) return;
        setIsUpdatingDetails(true);
        try {
            const collectionName = getResourceColName(villageId);
            const itemRef = doc(db, collectionName, editItemId);
            await updateDoc(itemRef, {
                unitCost: parseFloat(editItemUnitCost),
                category: editItemCategory,
                unit: editItemUnit,
                updatedAt: new Date().toISOString()
            });
            if(onSuccess) onSuccess(`Updated ${editItemName} details.`);
            setIsEditMatModalOpen(false);
        } catch (e) {
            console.error("Update details failed", e);
            alert("Failed to update details.");
        } finally {
            setIsUpdatingDetails(false);
        }
    };

    const handlePurchaseRequest = async (e: React.FormEvent) => {
        e.preventDefault();
        const selectedResource = resources.find(r => r.id === purchaseItemId);
        if (!selectedResource) return;
        try {
            const finColName = getFinancialCollectionName(villageId);
            const transactionId = "TXN-" + Date.now().toString().slice(-6) + Math.floor(100 + Math.random() * 900);
            const totalCost = parseFloat(purchaseCost) || 0;
            const qty = parseFloat(purchaseQty) || 1;
            const factor = selectedResource.unit === 'L' ? 10 : 1;
            const calcUnitCost = totalCost / (qty / factor);

            await setDoc(doc(db, finColName, transactionId), {
                type: 'EXPENSE',
                status: 'PENDING',
                category: 'Supplies', 
                amount: totalCost,
                date: new Date().toISOString().split('T')[0],
                description: `Purchase Request: ${purchaseQty} ${selectedResource.unit} of ${selectedResource.name} (${selectedResource.materialId || 'No ID'}). Est Unit Cost: RM${calcUnitCost.toFixed(2)} per ${selectedResource.unit === 'L' ? '10L' : selectedResource.unit}. Notes: ${purchaseNotes}`,
                recordedBy: userEmail,
                villageId: villageId,
                transactionId,
                materialId: selectedResource.id, // Linked Material ID for tracking
                orderQty: qty,
                receivedInStock: false,
                createdAt: new Date().toISOString()
            });
            setActiveNotification({
                title: "Purchase Request Sent",
                message: `Request for ${selectedResource.name} (Ref: ${transactionId}) has been sent to Finance.`
            });
            setIsPurchaseModalOpen(false);
            setPurchaseItemId(''); setPurchaseQty(''); setPurchaseCost(''); setPurchaseNotes('');
        } catch (e) {
            console.error("Purchase request failed", e);
            alert("Failed to send request.");
        }
    };

    const handleConfirmReceipt = async (rec: FinancialRecord) => {
        if (!rec.materialId) return;
        setIsConfirmingReceipt(rec.id);
        
        try {
            const inputVal = receivedInputs[rec.id];
            const orderQty = rec.orderQty || (() => {
                const match = rec.description?.match(/Purchase Request: ([\d.]+) /);
                return match ? parseFloat(match[1]) : 0;
            })();
            
            const actualQty = inputVal ? parseFloat(inputVal) : orderQty;
            
            if (isNaN(actualQty) || actualQty < 0) throw new Error("Please enter a valid received quantity.");

            const resColName = getResourceColName(villageId);
            const itemRef = doc(db, resColName, rec.materialId);
            const finColName = getFinancialCollectionName(villageId);
            const finRef = doc(db, finColName, rec.id);

            await updateDoc(itemRef, {
                quantity: increment(actualQty),
                updatedAt: new Date().toISOString()
            });

            await addDoc(collection(db, resColName, rec.materialId, "stock_history"), {
                type: 'IN', 
                quantity: actualQty,
                reason: `Supply Delivery Confirmed (Ref: ${rec.transactionId}) ${actualQty !== orderQty ? `[DISCREPANCY: Ordered ${orderQty}]` : ''}`,
                user: userEmail,
                timestamp: new Date().toISOString()
            });

            await updateDoc(finRef, {
                receivedInStock: true,
                orderQty: orderQty, 
                actualReceivedQty: actualQty,
                updatedAt: new Date().toISOString(),
                varianceResolved: actualQty === orderQty 
            });

            if (onSuccess) onSuccess(`Stock updated: +${actualQty} received for supply ${rec.transactionId}`);
            
            const newInputs = { ...receivedInputs };
            delete newInputs[rec.id];
            setReceivedInputs(newInputs);

        } catch (e: any) {
            console.error("Confirmation failed", e);
            alert("Error confirming receipt: " + e.message);
        } finally {
            setIsConfirmingReceipt(null);
        }
    };

    const totalProcessedStock = inventory.reduce((acc, item) => acc + (item.quantity || 0), 0);
    const totalAvailableStock = totalProcessedStock + totalCurrentStock;
    const ringClass = theme?.ring || "focus:ring-indigo-500";

    const equipmentList = resources.filter(r => r.category === 'Equipment');
    const materialList = resources.filter(r => r.category !== 'Equipment');

    return (
        <div className="space-y-6 animate-fade-in-up relative">
            {/* History Drawer */}
            {isHistoryDrawerOpen && historyMaterial && (
                <div className="fixed inset-0 z-[70] overflow-hidden">
                    <div className="absolute inset-0 bg-gray-500 bg-opacity-75 transition-opacity" onClick={() => setIsHistoryDrawerOpen(false)}></div>
                    <div className="fixed inset-y-0 right-0 pl-10 max-w-full flex">
                        <div className="w-screen max-w-md animate-slide-in-right">
                            <div className="h-full flex flex-col bg-white shadow-xl overflow-y-scroll">
                                <div className="py-6 px-4 bg-indigo-700 sm:px-6">
                                    <div className="flex items-center justify-between">
                                        <h2 className="text-lg font-medium text-white" id="slide-over-title">
                                            {historyMaterial.name} History
                                        </h2>
                                        <div className="ml-3 h-7 flex items-center">
                                            <button type="button" className="bg-indigo-700 rounded-md text-indigo-200 hover:text-white focus:outline-none" onClick={() => setIsHistoryDrawerOpen(false)}>
                                                <span className="sr-only">Close panel</span>
                                                <svg className="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
                                                </svg>
                                            </button>
                                        </div>
                                    </div>
                                    <div className="mt-1">
                                        <p className="text-sm text-indigo-300">
                                            Stock ID: {historyMaterial.materialId || historyMaterial.id}
                                        </p>
                                    </div>
                                </div>
                                <div className="relative flex-1 py-6 px-4 sm:px-6">
                                    {loadingHistory ? (
                                        <div className="flex justify-center mt-10"><div className="animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-600"></div></div>
                                    ) : (
                                        <div className="flow-root">
                                            <ul className="-mb-8">
                                                {historyLogs.length === 0 ? (
                                                    <li className="text-center text-gray-500 text-sm italic">No history found.</li>
                                                ) : (
                                                    historyLogs.map((log, logIdx) => (
                                                        <li key={log.id}>
                                                            <div className="relative pb-8">
                                                                {logIdx !== historyLogs.length - 1 ? (
                                                                    <span className="absolute top-4 left-4 -ml-px h-full w-0.5 bg-gray-200" aria-hidden="true"></span>
                                                                ) : null}
                                                                <div className="relative flex space-x-3">
                                                                    <div>
                                                                        <span className={`h-8 w-8 rounded-full flex items-center justify-center ring-8 ring-white ${log.type === 'IN' ? 'bg-green-500' : 'bg-red-500'}`}>
                                                                            {log.type === 'IN' ? (
                                                                                <svg className="h-5 w-5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6v6m0 0v6m0-6h6m-6 0H6" /></svg>
                                                                            ) : (
                                                                                <svg className="h-5 w-5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20 12H4" /></svg>
                                                                            )}
                                                                        </span>
                                                                    </div>
                                                                    <div className="min-w-0 flex-1 pt-1.5 flex justify-between space-x-4">
                                                                        <div>
                                                                            <p className="text-sm text-gray-500">
                                                                                {log.type === 'IN' ? 'Added' : 'Deducted'} <span className="font-medium text-gray-900">{log.quantity} {historyMaterial.unit}</span>
                                                                            </p>
                                                                            <p className="text-xs text-gray-400 mt-0.5">{log.reason}</p>
                                                                        </div>
                                                                        <div className="text-right text-sm whitespace-nowrap text-gray-500">
                                                                            <time dateTime={log.timestamp}>{new Date(log.timestamp).toLocaleDateString()}</time>
                                                                            <div className="text-[10px] text-gray-400">{new Date(log.timestamp).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})}</div>
                                                                            <div className="text-[10px] font-medium text-indigo-600 mt-1">{log.user ? log.user.split('@')[0] : 'System'}</div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </li>
                                                    ))
                                                )}
                                            </ul>
                                        </div>
                                    )}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            )}

            {/* Notification Toast */}
            {activeNotification && (
                <div className="fixed bottom-6 right-6 z-[60] max-w-sm w-full bg-white border-l-4 border-indigo-600 shadow-2xl rounded-r-lg pointer-events-auto transform transition-all duration-300 ease-in-out translate-y-0 opacity-100">
                    <div className="p-4">
                        <div className="flex items-start">
                            <div className="flex-shrink-0">
                                <svg className="h-6 w-6 text-indigo-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                                </svg>
                            </div>
                            <div className="ml-3 w-0 flex-1 pt-0.5">
                                <p className="text-sm font-bold text-gray-900">{activeNotification.title}</p>
                                <p className="mt-1 text-sm text-gray-500">{activeNotification.message}</p>
                                <div className="mt-4 flex">
                                    <button onClick={() => setActiveNotification(null)} className="inline-flex items-center px-3 py-1.5 border border-transparent text-xs font-medium rounded-md text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">Mark as Read</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            )}

            {/* KPI Section */}
            <div className={`grid grid-cols-1 ${villageId === VillageType.C ? 'md:grid-cols-3' : 'md:grid-cols-4'} gap-4`}>
                <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm relative overflow-hidden">
                    <div className="relative z-10">
                        <h3 className="text-[10px] font-black text-gray-400 uppercase tracking-widest mb-1">Total Yield (Aggregate)</h3>
                        <div className="flex items-baseline gap-2">
                            <span className="text-3xl font-black text-green-600">{yieldStats.total.toFixed(1)}</span>
                            <span className="text-sm text-gray-400 font-bold">kg</span>
                            {yieldStats.change !== 0 && (
                                <span className={`text-[10px] font-black px-1.5 py-0.5 rounded-lg flex items-center gap-0.5 ${yieldStats.change > 0 ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'}`}>
                                    {yieldStats.change > 0 ? '▲' : '▼'} {Math.abs(yieldStats.change).toFixed(1)}%
                                </span>
                            )}
                        </div>
                        <p className="text-[9px] text-gray-400 font-bold uppercase mt-1">vs last batch cycle</p>
                    </div>
                </div>

                <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm relative overflow-hidden">
                    <div className="relative z-10">
                        <h3 className="text-[10px] font-black text-gray-400 uppercase tracking-widest mb-1">Total Sold (Aggregate)</h3>
                        <div className="flex items-baseline gap-1">
                            <span className="text-3xl font-black text-indigo-600">{salesRevenue.totalWeight.toFixed(1)}</span>
                            <span className="text-sm text-gray-400 font-bold">kg</span>
                        </div>
                        <p className="text-[10px] text-indigo-500 font-black uppercase mt-1">Revenue: RM{salesRevenue.revenue.toLocaleString()}</p>
                    </div>
                </div>

                <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm relative overflow-hidden">
                    <div className="relative z-10">
                        <h3 className="text-[10px] font-black text-gray-400 uppercase tracking-widest mb-1">Available Hub Supply</h3>
                        <div className="flex items-baseline gap-1">
                            <span className="text-3xl font-black text-blue-600">{(totalAvailableStock || 0).toFixed(1)}</span>
                            <span className="text-sm text-gray-400 font-bold">kg</span>
                        </div>
                        <p className={`text-[10px] font-black uppercase mt-1 ${supplyDays < 5 ? 'text-red-600 animate-pulse' : 'text-blue-500'}`}>
                            ≈ {supplyDays > 0 ? supplyDays.toFixed(0) : '--'} days of supply remaining
                        </p>
                    </div>
                </div>

                {villageId !== VillageType.C && (
                    <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm relative overflow-hidden border-l-4 border-l-indigo-500">
                        <div className="relative z-10">
                            <h3 className="text-[10px] font-black text-indigo-500 uppercase tracking-widest mb-1">Inventory Assets</h3>
                            <div className="flex items-baseline gap-1">
                                <span className="text-sm font-bold text-gray-400">RM</span>
                                <span className="text-3xl font-black text-indigo-700">{(totalResourceValue || 0).toLocaleString(undefined, {minimumFractionDigits: 2})}</span>
                            </div>
                            {resourceAtRisk > 0 && (
                                <p className="text-[10px] text-red-600 font-black uppercase mt-1 flex items-center gap-1">
                                    <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
                                    RM{resourceAtRisk.toLocaleString()} at risk (low stock)
                                </p>
                            )}
                        </div>
                    </div>
                )}
            </div>

            {/* Pending Receipts Logic */}
            {villageId !== VillageType.C && pendingReceipts.length > 0 && (
                <div className="bg-orange-50 rounded-xl border border-orange-100 overflow-hidden animate-fade-in shadow-sm">
                    <div className="px-6 py-4 border-b border-orange-200 bg-orange-100/50 flex justify-between items-center">
                        <div>
                            <h3 className="text-sm font-black text-orange-900 uppercase tracking-tight flex items-center gap-2">
                                <span className="relative flex h-3 w-3">
                                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-orange-400 opacity-75"></span>
                                  <span className="relative inline-flex rounded-full h-3 w-3 bg-orange-500"></span>
                                </span>
                                Action Required: Confirm Receipts
                            </h3>
                            <p className="text-[10px] text-orange-700 font-bold uppercase mt-1">Supplies paid for but not yet marked as 'In Stock'</p>
                        </div>
                        <span className="bg-orange-200 text-orange-800 text-xs font-bold px-3 py-1 rounded-full">{pendingReceipts.length} Pending</span>
                    </div>
                    <div className="overflow-x-auto">
                        <table className="min-w-full divide-y divide-orange-100">
                            <thead className="bg-orange-50/50">
                                <tr className="text-[9px] font-black text-orange-600 uppercase tracking-widest">
                                    <th className="px-6 py-3 text-left">Ref ID</th>
                                    <th className="px-6 py-3 text-left">Material Name</th>
                                    <th className="px-6 py-3 text-right">Order Qty</th>
                                    <th className="px-6 py-3 text-center">Actual Received Qty</th>
                                    <th className="px-6 py-3 text-left">Payment Date</th>
                                    <th className="px-6 py-3 text-center">Action</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-orange-100">
                                {pendingReceipts.map(rec => {
                                    const resource = resources.find(r => r.id === rec.materialId);
                                    const orderQty = rec.orderQty || 0;
                                    const currentInput = receivedInputs[rec.id];
                                    const actualQty = currentInput ? parseFloat(currentInput) : orderQty;
                                    const hasDiscrepancy = actualQty !== orderQty;

                                    return (
                                        <tr key={rec.id} className="hover:bg-orange-100/30 transition-colors">
                                            <td className="px-6 py-4 whitespace-nowrap text-[10px] font-mono font-bold text-orange-900">{rec.transactionId}</td>
                                            <td className="px-6 py-4 whitespace-nowrap text-xs font-bold text-gray-700">
                                                {resource?.name || 'Unknown Material'}
                                                <div className="text-[9px] text-gray-400 font-normal uppercase">{rec.materialId}</div>
                                            </td>
                                            <td className="px-6 py-4 whitespace-nowrap text-sm font-black text-right text-gray-400">
                                                {orderQty} <span className="text-[9px] font-bold">{resource?.unit || ''}</span>
                                            </td>
                                            <td className="px-6 py-4 whitespace-nowrap text-center">
                                                <div className="inline-flex items-center gap-2">
                                                    <input 
                                                        type="number" 
                                                        step="any"
                                                        value={currentInput ?? orderQty}
                                                        onChange={(e) => setReceivedInputs({...receivedInputs, [rec.id]: e.target.value})}
                                                        className={`w-24 p-1.5 border rounded-lg text-xs font-black text-center focus:ring-2 focus:ring-orange-500 transition-all ${hasDiscrepancy ? 'border-red-400 bg-red-50 text-red-700' : 'border-gray-200 bg-white text-gray-700'}`}
                                                    />
                                                </div>
                                            </td>
                                            <td className="px-6 py-4 whitespace-nowrap text-[10px] font-bold text-gray-500 uppercase">{rec.settledDate || rec.date}</td>
                                            <td className="px-6 py-4 whitespace-nowrap text-center">
                                                <button 
                                                    onClick={() => handleConfirmReceipt(rec)}
                                                    disabled={isConfirmingReceipt === rec.id}
                                                    className={`px-3 py-1.5 text-white text-[10px] font-black uppercase rounded-lg shadow-md transition-all flex items-center gap-2 mx-auto disabled:opacity-50 ${hasDiscrepancy ? 'bg-red-600 hover:bg-red-700' : 'bg-orange-600 hover:bg-orange-700'}`}
                                                >
                                                    {isConfirmingReceipt === rec.id ? 'Saving...' : hasDiscrepancy ? 'Confirm Partial' : 'Confirm Received'}
                                                </button>
                                            </td>
                                        </tr>
                                    );
                                })}
                            </tbody>
                        </table>
                    </div>
                </div>
            )}

            {/* Material Table and Action Buttons */}
            {villageId !== VillageType.C && (
                <>
                    <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
                        <div className="px-6 py-4 border-b border-gray-200 bg-gray-50 flex flex-col sm:flex-row justify-between items-start sm:items-center">
                            <div>
                                <h2 className="text-lg font-black text-gray-900 tracking-tight">Material Availability (Inputs)</h2>
                                <p className="text-xs text-gray-400 font-medium">Costing and quantity control for raw supplies.</p>
                            </div>
                            <div className="mt-2 sm:mt-0 flex gap-2">
                                <button onClick={handleAutoSetThresholds} className="px-4 py-2.5 bg-orange-50 text-orange-600 border border-orange-200 text-xs font-black uppercase rounded-xl shadow-sm hover:bg-orange-100 transition-all flex items-center gap-2">
                                    Enforce Safe Limits (30kg)
                                </button>
                                <button onClick={() => setShowSupplyHistory(!showSupplyHistory)} className="px-4 py-2.5 bg-white text-blue-600 border border-blue-200 text-xs font-black uppercase rounded-xl shadow-sm hover:bg-blue-50 transition-all flex items-center gap-2">
                                    {showSupplyHistory ? 'Hide History' : 'Supply History'}
                                </button>
                                <button onClick={() => { setIsAddMatModalOpen(true); }} className="px-4 py-2.5 bg-white text-gray-700 border border-gray-200 text-xs font-black uppercase rounded-xl shadow-sm hover:bg-gray-50 transition-all flex items-center gap-2">
                                    New Material
                                </button>
                                <button onClick={() => { setPurchaseItemId(''); setIsPurchaseModalOpen(true); }} className="px-4 py-2.5 bg-indigo-600 text-white hover:bg-indigo-700 text-xs font-black uppercase rounded-xl shadow-lg transition-all flex items-center gap-2">
                                    Purchase
                                </button>
                            </div>
                        </div>

                        {showSupplyHistory && (
                            <div className="bg-slate-50 border-b border-gray-200 p-4 animate-fade-in">
                                <h4 className="text-xs font-bold text-gray-500 uppercase mb-3 ml-2">Recent Confirmed Arrivals</h4>
                                <div className="overflow-x-auto">
                                    <table className="min-w-full divide-y divide-gray-200 text-xs bg-white rounded-lg border border-gray-200 shadow-sm">
                                        <thead className="bg-gray-100">
                                            <tr><th className="px-4 py-2 text-left text-gray-500">Date Received</th><th className="px-4 py-2 text-left text-gray-500">Transaction ID</th><th className="px-4 py-2 text-left text-gray-500">Item</th><th className="px-4 py-2 text-right text-gray-500">Qty Received</th><th className="px-4 py-2 text-right text-gray-500">Cost</th></tr>
                                        </thead>
                                        <tbody className="divide-y divide-gray-100">
                                            {receivedSuppliesHistory.map(rec => {
                                                const res = resources.find(r => r.id === rec.materialId);
                                                return (
                                                    <tr key={rec.id} className="hover:bg-gray-50">
                                                        <td className="px-4 py-2 text-gray-500">{new Date(rec.updatedAt || rec.date).toLocaleDateString()}</td>
                                                        <td className="px-4 py-2 font-mono">{rec.transactionId}</td>
                                                        <td className="px-4 py-2 font-bold">{res?.name || 'Unknown'}</td>
                                                        <td className="px-4 py-2 text-right text-green-600 font-bold">+{rec.actualReceivedQty || rec.orderQty} {res?.unit}</td>
                                                        <td className="px-4 py-2 text-right">RM{rec.amount.toFixed(2)}</td>
                                                    </tr>
                                                );
                                            })}
                                            {receivedSuppliesHistory.length === 0 && <tr><td colSpan={5} className="text-center py-4 text-gray-400 italic">No history available</td></tr>}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        )}

                        <div className="overflow-x-auto">
                            <table className="min-w-full divide-y divide-gray-100">
                                <thead className="bg-gray-50/50">
                                    <tr className="text-[10px] font-black text-gray-400 uppercase tracking-widest">
                                        <th className="px-6 py-4 text-left">Item Details</th>
                                        <th className="px-6 py-4 text-left">Category</th>
                                        <th className="px-6 py-4 text-right">Quantity</th>
                                        <th className="px-6 py-4 text-right">Pending Received</th>
                                        <th className="px-6 py-4 text-right">Unit Cost (RM)</th>
                                        <th className="px-6 py-4 text-center">Availability</th>
                                        <th className="px-6 py-4 text-center">Low Stock Limit</th>
                                    </tr>
                                </thead>
                                <tbody className="bg-white divide-y divide-gray-100">
                                    {loading ? (
                                        <tr><td colSpan={7} className="px-6 py-12 text-center text-sm text-gray-400 italic">Loading resources...</td></tr>
                                    ) : materialList.length === 0 ? (
                                        <tr><td colSpan={7} className="px-6 py-12 text-center text-sm text-gray-400 italic">No resources tracked for {villageId} yet.</td></tr>
                                    ) : (
                                        materialList.map((item) => {
                                            const quantity = item.quantity || 0;
                                            const pending = pendingWeightsByResource[item.id] || 0;
                                            const unitCost = item.unitCost || 0;
                                            const isLow = quantity <= item.lowStockThreshold;
                                            const isCritical = quantity <= (item.lowStockThreshold * 0.2);
                                            return (
                                                <tr key={item.id} className="hover:bg-gray-50 transition-colors">
                                                    <td className="px-6 py-5 whitespace-nowrap cursor-pointer group" onClick={() => handleViewHistory(item)}>
                                                        <div className="text-sm font-black text-gray-900 group-hover:text-indigo-600 transition-colors flex items-center gap-2">
                                                            {item.name}
                                                            <svg className="w-4 h-4 text-gray-300 group-hover:text-indigo-400 opacity-0 group-hover:opacity-100 transition-all" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01" /></svg>
                                                        </div>
                                                        <div className="text-[10px] text-gray-400 font-bold uppercase tracking-tight">{item.materialId || item.id}</div>
                                                    </td>
                                                    <td className="px-6 py-5 whitespace-nowrap">
                                                        <span className="px-2.5 py-1 rounded-lg text-[10px] font-black uppercase bg-gray-100 text-gray-500 border border-gray-200">{item.category}</span>
                                                    </td>
                                                    <td className="px-6 py-5 whitespace-nowrap text-sm font-black text-right text-gray-900">
                                                        {quantity.toLocaleString()} <span className="text-gray-400 font-bold text-[10px] ml-0.5">{item.unit}</span>
                                                    </td>
                                                    <td className="px-6 py-5 whitespace-nowrap text-sm font-black text-right text-orange-600">
                                                        {pending > 0 ? `+${pending.toLocaleString()} ${item.unit}` : '-'}
                                                    </td>
                                                    <td className="px-6 py-5 whitespace-nowrap text-sm font-bold text-right text-gray-500">
                                                        {unitCost.toFixed(2)} <span className="text-[9px] text-gray-400">/ {item.unit === 'L' ? '10L' : item.unit}</span>
                                                    </td>
                                                    <td className="px-6 py-5 whitespace-nowrap text-center">
                                                        {isCritical ? (
                                                            <span className="px-3 py-1 text-[10px] font-black uppercase rounded-full bg-red-100 text-red-700 border border-red-200 animate-pulse">Critical</span>
                                                        ) : isLow ? (
                                                            <span className="px-3 py-1 text-[10px] font-black uppercase rounded-full bg-yellow-100 text-yellow-800 border border-yellow-200">Low Stock</span>
                                                        ) : (
                                                            <span className="px-3 py-1 text-[10px] font-black uppercase rounded-full bg-green-100 text-green-800 border border-green-200">OK</span>
                                                        )}
                                                    </td>
                                                    <td className="px-6 py-5 whitespace-nowrap text-center text-xs font-bold text-gray-500">
                                                        {item.lowStockThreshold} {item.unit}
                                                    </td>
                                                </tr>
                                            );
                                        })
                                    )}
                                </tbody>
                            </table>
                        </div>
                    </div>

                    {/* Equipment Table */}
                    <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden mt-6">
                        <div className="px-6 py-4 border-b border-gray-200 bg-gray-50 flex justify-between items-center">
                            <div>
                                <h2 className="text-lg font-black text-gray-900 tracking-tight">Facility Equipment & Hardware</h2>
                                <p className="text-xs text-gray-400 font-medium">Active environmental control systems.</p>
                            </div>
                            <div className="text-[10px] font-bold uppercase text-gray-400 bg-gray-100 px-3 py-1 rounded-full">
                                System Status: {latestEnvLog ? `Monitoring (${latestEnvLog.temperature}°C / ${latestEnvLog.humidity}%)` : 'Syncing...'}
                            </div>
                        </div>
                        <div className="overflow-x-auto">
                            <table className="min-w-full divide-y divide-gray-100">
                                <thead className="bg-gray-50/50">
                                    <tr className="text-[10px] font-black text-gray-400 uppercase tracking-widest">
                                        <th className="px-6 py-4 text-left">Equipment Name</th>
                                        <th className="px-6 py-4 text-left">Location (Linked)</th>
                                        <th className="px-6 py-4 text-center">Availability</th>
                                        <th className="px-6 py-4 text-right">Quantity</th>
                                    </tr>
                                </thead>
                                <tbody className="bg-white divide-y divide-gray-100">
                                    {equipmentList.length === 0 ? (
                                        <tr><td colSpan={4} className="px-6 py-12 text-center text-sm text-gray-400 italic">No equipment logged.</td></tr>
                                    ) : (
                                        equipmentList.map((item) => {
                                            // Availability Calculation
                                            const totalQty = item.quantity || 0;
                                            const locations = item.location ? item.location.split(',').map(s => s.trim()).filter(Boolean) : [];
                                            const inUseCount = locations.length;
                                            const availableCount = Math.max(0, totalQty - inUseCount);
                                            const isUnavailable = availableCount === 0;

                                            return (
                                                <tr key={item.id} className="hover:bg-gray-50 transition-colors">
                                                    <td className="px-6 py-5 whitespace-nowrap">
                                                        <div className="text-sm font-black text-gray-900">{item.name}</div>
                                                        <div className="text-[10px] text-gray-400 font-bold uppercase tracking-tight">{item.materialId || item.id}</div>
                                                    </td>
                                                    <td className="px-6 py-5 whitespace-nowrap text-xs font-bold text-gray-600">
                                                        {locations.length > 0 ? (
                                                            <div className="flex flex-wrap gap-1 max-w-[200px]">
                                                                {locations.map((loc, i) => (
                                                                    <span key={i} className="bg-indigo-50 text-indigo-700 px-2 py-0.5 rounded border border-indigo-100">{loc}</span>
                                                                ))}
                                                            </div>
                                                        ) : (
                                                            <span className="text-gray-400 italic">Not assigned</span>
                                                        )}
                                                    </td>
                                                    <td className="px-6 py-5 whitespace-nowrap text-center">
                                                        <span className={`px-3 py-1 rounded-full text-[10px] font-black uppercase ${isUnavailable ? 'bg-red-50 text-red-600' : 'bg-green-100 text-green-700'}`}>
                                                            {isUnavailable ? 'Unavailable' : `${availableCount} Available`}
                                                        </span>
                                                    </td>
                                                    <td className="px-6 py-5 whitespace-nowrap text-sm font-black text-right text-gray-900">
                                                        {totalQty} <span className="text-gray-400 font-bold text-[10px]">{item.unit}</span>
                                                    </td>
                                                </tr>
                                            );
                                        })
                                    )}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </>
            )}

            {/* Modals */}
            {isTransModalOpen && selectedItem && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
                    <div className="bg-white rounded-lg p-6 w-full max-w-sm">
                        <h3 className="text-lg font-bold mb-4">Adjust Stock: {selectedItem.name}</h3>
                        <form onSubmit={handleTransaction}>
                            <div className="flex gap-4 mb-4">
                                <label className="flex items-center gap-2 cursor-pointer">
                                    <input type="radio" name="transType" checked={transType==='IN'} onChange={()=>setTransType('IN')} />
                                    <span>Add Stock (IN)</span>
                                </label>
                                <label className="flex items-center gap-2 cursor-pointer">
                                    <input type="radio" name="transType" checked={transType==='OUT'} onChange={()=>setTransType('OUT')} />
                                    <span>Deduct Stock (OUT)</span>
                                </label>
                            </div>
                            <input type="number" required step="0.01" value={transQty} onChange={e=>setTransQty(e.target.value)} className="w-full border rounded p-2 mb-3" placeholder={`Quantity (${selectedItem.unit})`} />
                            <input type="text" value={transReason} onChange={e=>setTransReason(e.target.value)} className="w-full border rounded p-2 mb-4" placeholder="Reason (e.g. Restock, Usage)" />
                            <div className="flex justify-end gap-2">
                                <button type="button" onClick={()=>setIsTransModalOpen(false)} className="px-4 py-2 bg-gray-200 rounded">Cancel</button>
                                <button type="submit" className="px-4 py-2 bg-blue-600 text-white rounded">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            )}

            {isAddMatModalOpen && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-gray-900/60 backdrop-blur-sm p-4">
                    <div className="bg-white rounded-3xl shadow-2xl w-full max-w-md p-8 animate-scale-up">
                        <div className="mb-6">
                            <h3 className="text-2xl font-black text-gray-900 tracking-tight">Register New Material</h3>
                            <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mt-1">Add a new item to inventory tracking</p>
                        </div>
                        <form onSubmit={handleAddMaterial} className="space-y-5">
                            <div>
                                <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1.5">Material Name</label>
                                <input type="text" required value={newMatName} onChange={e=>setNewMatName(e.target.value)} className="w-full bg-gray-50 border-transparent focus:bg-white focus:border-gray-200 focus:ring-0 rounded-xl px-4 py-3.5 text-sm font-bold text-gray-800 placeholder-gray-300 transition-all" placeholder="e.g. Bio-Substrate X" />
                            </div>
                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1.5">Category</label>
                                    <div className="relative">
                                        <select value={newMatCategory} onChange={e=>setNewMatCategory(e.target.value)} className="w-full bg-gray-50 border-transparent focus:bg-white focus:border-gray-200 focus:ring-0 rounded-xl px-4 py-3.5 text-sm font-bold text-gray-800 appearance-none">
                                            <option value="Input">Input</option>
                                            <option value="Nutrient">Nutrient</option>
                                            <option value="Utility">Utility</option>
                                            <option value="Equipment">Equipment</option>
                                        </select>
                                        <div className="absolute inset-y-0 right-0 flex items-center px-3 pointer-events-none text-gray-400">
                                            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7"></path></svg>
                                        </div>
                                    </div>
                                </div>
                                <div>
                                    <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1.5">Unit</label>
                                    <div className="relative">
                                         <select value={newMatUnit} onChange={e=>setNewMatUnit(e.target.value)} className="w-full bg-gray-50 border-transparent focus:bg-white focus:border-gray-200 focus:ring-0 rounded-xl px-4 py-3.5 text-sm font-bold text-gray-800 appearance-none">
                                            <option value="kg">kg</option>
                                            <option value="L">L</option>
                                            <option value="units">units</option>
                                            <option value="packs">packs</option>
                                        </select>
                                        <div className="absolute inset-y-0 right-0 flex items-center px-3 pointer-events-none text-gray-400">
                                            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7"></path></svg>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="grid grid-cols-3 gap-4">
                                <div>
                                    <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1.5">Initial Qty</label>
                                    <input type="number" required step="0.01" value={newMatQty} onChange={e=>setNewMatQty(e.target.value)} className="w-full bg-gray-50 border-transparent focus:bg-white focus:border-gray-200 focus:ring-0 rounded-xl px-4 py-3.5 text-sm font-bold text-gray-800 placeholder-gray-300 transition-all" placeholder="0" />
                                </div>
                                <div>
                                    <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1.5">Low Alert</label>
                                    <input type="number" required step="0.01" value={newMatThreshold} onChange={e=>setNewMatThreshold(e.target.value)} className="w-full bg-gray-50 border-transparent focus:bg-white focus:border-gray-200 focus:ring-0 rounded-xl px-4 py-3.5 text-sm font-bold text-gray-800 placeholder-gray-300 transition-all" placeholder="Min" />
                                </div>
                                <div>
                                    <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1.5">Cost/Unit</label>
                                    <input type="number" required step="0.01" value={newMatUnitCost} onChange={e=>setNewMatUnitCost(e.target.value)} className="w-full bg-gray-50 border-transparent focus:bg-white focus:border-gray-200 focus:ring-0 rounded-xl px-4 py-3.5 text-sm font-bold text-gray-800 placeholder-gray-300 transition-all" placeholder="RM" />
                                </div>
                            </div>
                            <div className="flex gap-4 pt-2">
                                <button type="button" onClick={()=>setIsAddMatModalOpen(false)} className="flex-1 bg-white border-2 border-gray-100 text-gray-700 font-black py-4 rounded-xl hover:bg-gray-50 transition-colors uppercase text-xs tracking-wider">Cancel</button>
                                <button type="submit" className="flex-1 bg-green-600 text-white font-black py-4 rounded-xl hover:bg-green-700 shadow-xl shadow-green-200 transition-all transform hover:-translate-y-0.5 uppercase text-xs tracking-wider">Save Material</button>
                            </div>
                        </form>
                    </div>
                </div>
            )}

            {isEditMatModalOpen && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
                    <div className="bg-white rounded-lg p-6 w-full max-w-sm">
                        <h3 className="text-lg font-bold mb-4">Edit {editItemName}</h3>
                        <form onSubmit={handleUpdateDetails} className="space-y-3">
                            <div>
                                <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Cost Per Unit (RM)</label>
                                <input type="number" required step="0.01" value={editItemUnitCost} onChange={e=>setEditItemUnitCost(e.target.value)} className="w-full border rounded p-2" />
                            </div>
                            <div>
                                <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Category</label>
                                <select value={editItemCategory} onChange={e=>setEditItemCategory(e.target.value)} className="w-full border rounded p-2">
                                    <option value="Input">Input</option><option value="Nutrient">Nutrient</option><option value="Utility">Utility</option><option value="Equipment">Equipment</option>
                                </select>
                            </div>
                            <div>
                                <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Unit</label>
                                <input type="text" required value={editItemUnit} onChange={e=>setEditItemUnit(e.target.value)} className="w-full border rounded p-2" />
                            </div>
                            <div className="flex justify-end gap-2 mt-4">
                                <button type="button" onClick={()=>setIsEditMatModalOpen(false)} className="px-4 py-2 bg-gray-200 rounded">Cancel</button>
                                <button type="submit" disabled={isUpdatingDetails} className="px-4 py-2 bg-blue-600 text-white rounded">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            )}

            {isPurchaseModalOpen && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-gray-900/60 backdrop-blur-sm p-4">
                    <div className="bg-white rounded-3xl shadow-2xl w-full max-w-md p-8 animate-scale-up text-center">
                        <div className="mx-auto h-16 w-16 bg-indigo-50 rounded-2xl flex items-center justify-center mb-6 shadow-inner">
                            <svg className="w-8 h-8 text-indigo-600" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" /></svg>
                        </div>
                        <h3 className="text-2xl font-black text-gray-900 tracking-tight">Initiate Purchase</h3>
                        <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mt-1 mb-8">Submit order to finance dept</p>
                        
                        <form onSubmit={handlePurchaseRequest} className="space-y-5 text-left">
                            <div>
                                <div className="flex justify-between items-center mb-1.5">
                                    <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Material to Restock</label>
                                    <button type="button" onClick={() => { setIsPurchaseModalOpen(false); setIsAddMatModalOpen(true); }} className="text-[10px] font-bold text-indigo-600 hover:text-indigo-800 uppercase tracking-wide">Create New?</button>
                                </div>
                                <div className="relative">
                                    <select value={purchaseItemId} onChange={e=>setPurchaseItemId(e.target.value)} className="w-full bg-gray-50 border-transparent focus:bg-white focus:border-gray-200 focus:ring-0 rounded-xl px-4 py-3.5 text-sm font-bold text-gray-800 appearance-none">
                                        <option value="">-- Select Resource --</option>
                                        {resources.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}
                                    </select>
                                    <div className="absolute inset-y-0 right-0 flex items-center px-3 pointer-events-none text-gray-400">
                                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7"></path></svg>
                                    </div>
                                </div>
                                {selectedPurchaseResource && (
                                    <div className="text-right mt-1">
                                        <span className="text-[10px] font-bold text-indigo-500 bg-indigo-50 px-2 py-0.5 rounded">
                                            Unit Price: RM {selectedPurchaseResource.unitCost.toFixed(2)} per {selectedPurchaseResource.unit === 'L' ? '10L' : selectedPurchaseResource.unit}
                                        </span>
                                    </div>
                                )}
                            </div>
                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1.5">Quantity to Buy</label>
                                    <input type="number" required step="0.01" value={purchaseQty} onChange={e=>setPurchaseQty(e.target.value)} className="w-full bg-gray-50 border-transparent focus:bg-white focus:border-gray-200 focus:ring-0 rounded-xl px-4 py-3.5 text-sm font-bold text-gray-800 placeholder-gray-300 transition-all text-center" placeholder="0.00" />
                                </div>
                                <div>
                                    <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1.5">Total Cost (RM)</label>
                                    <input type="number" required step="0.01" value={purchaseCost} onChange={e=>setPurchaseCost(e.target.value)} className="w-full bg-gray-50 border-transparent focus:bg-white focus:border-gray-200 focus:ring-0 rounded-xl px-4 py-3.5 text-sm font-bold text-gray-800 placeholder-gray-300 transition-all text-center" placeholder="0.00" />
                                </div>
                            </div>
                            <div>
                                <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1.5">Suppliers / Notes</label>
                                <textarea value={purchaseNotes} onChange={e=>setPurchaseNotes(e.target.value)} className="w-full bg-gray-50 border-transparent focus:bg-white focus:border-gray-200 focus:ring-0 rounded-xl px-4 py-3.5 text-sm font-bold text-gray-800 placeholder-gray-300 transition-all min-h-[80px]" placeholder="e.g. Urgent, Main Supplier ABC" />
                            </div>
                            <div className="flex gap-4 pt-4">
                                <button type="button" onClick={()=>{setIsPurchaseModalOpen(false); setPurchaseItemId('');}} className="flex-1 bg-white border-2 border-gray-100 text-gray-800 font-black py-4 rounded-xl hover:bg-gray-50 transition-colors uppercase text-xs tracking-wider">Cancel</button>
                                <button type="submit" className="flex-1 bg-indigo-600 text-white font-black py-4 rounded-xl hover:bg-indigo-700 shadow-xl shadow-indigo-200 transition-all transform hover:-translate-y-0.5 uppercase text-xs tracking-wider">Submit Order</button>
                            </div>
                        </form>
                    </div>
                </div>
            )}
        </div>
    );
};
