import React, { useState, useEffect, useMemo } from 'react';
import { collection, onSnapshot, doc, updateDoc, addDoc, setDoc, query, where, getDocs, increment, Timestamp, orderBy, limit } from 'firebase/firestore';
import { db } from '../../services/firebase';
import { VillageType, HarvestLog, FinancialRecord } from '../../types';

interface FirestoreResource {
    id: string;
    materialId?: string; // Autogenerated readable ID
    name: string;
    quantity: number;
    unit: string;
    category: string;
    lowStockThreshold: number;
    unitCost: number; // Cost per 1 unit (RM), except for 'L' which is per 10 units
    updatedAt: any;
    // Equipment specific fields
    condition?: 'Excellent' | 'Good' | 'Fair' | 'Service Due';
    location?: string; // Comma separated list of rooms
    lastServiceDate?: string;
    operationStatus?: string; // Manual override status
}

interface InventoryItem {
    id: string;
    name: string;
    quantity: number;
    unit: string;
    status: 'Ready' | 'Hold';
    batchId?: string;
    updatedAt: any;
}

interface ResourcesTabProps {
    villageId: VillageType;
    userEmail: string;
    theme?: any;
    onSuccess?: (msg: string) => void;
    financialRecords: FinancialRecord[];
    initialPurchaseState?: { active: boolean, itemId?: string };
    onResetPurchaseState?: () => void;
}

// Requirements per 1kg of Mushroom Yield (Based on FarmingTab recipes)
const MATERIAL_REQUIREMENTS: Record<string, number> = {
    "MAT-573260995": 20,   // Straw (20kg per 1kg yield)
    "MAT-545594408": 75,   // Water (50+5+20 = 75L per 1kg yield)
    "MAT-406637503": 0.5,  // Bran (0.5kg per 1kg yield)
    "MAT-446059102": 0.2,  // Gypsum (0.2kg per 1kg yield)
    "MAT-282015830": 1,    // Spawn (1kg per 1kg yield)
};

export const ResourcesTab: React.FC<ResourcesTabProps> = ({ 
    villageId, userEmail, theme, onSuccess, financialRecords, initialPurchaseState, onResetPurchaseState 
}) => {
    // --- State ---
    const [resources, setResources] = useState<FirestoreResource[]>([]);
    const [inventory, setInventory] = useState<InventoryItem[]>([]);
    const [harvestLogs, setHarvestLogs] = useState<HarvestLog[]>([]); 
    const [loading, setLoading] = useState(true);
    
    // Environment Context for Equipment Status
    const [latestEnvLog, setLatestEnvLog] = useState<{temperature: number, humidity: number} | null>(null);

    // KPIs
    const [todayProduction, setTodayProduction] = useState(0);
    const [inventoryOutCount, setInventoryOutCount] = useState(0); 

    // Stock Transaction Modal State
    const [isTransModalOpen, setIsTransModalOpen] = useState(false);
    const [transType, setTransType] = useState<'IN' | 'OUT'>('IN');
    const [selectedItem, setSelectedItem] = useState<FirestoreResource | null>(null);
    const [transQty, setTransQty] = useState('');
    const [transReason, setTransReason] = useState('');

    // Add New Material Modal State
    const [isAddMatModalOpen, setIsAddMatModalOpen] = useState(false);
    const [newMatName, setNewMatName] = useState('');
    const [newMatCategory, setNewMatCategory] = useState('Input');
    const [newMatUnit, setNewMatUnit] = useState('kg');
    const [newMatQty, setNewMatQty] = useState('');
    const [newMatThreshold, setNewMatThreshold] = useState('');
    const [newMatUnitCost, setNewMatUnitCost] = useState('');

    // Edit Material Modal State
    const [isEditMatModalOpen, setIsEditMatModalOpen] = useState(false);
    const [editItemId, setEditItemId] = useState('');
    const [editItemName, setEditItemName] = useState('');
    const [editItemUnitCost, setEditItemUnitCost] = useState('');
    const [editItemCategory, setEditItemCategory] = useState('Input');
    const [editItemUnit, setEditItemUnit] = useState('kg');
    const [isUpdatingDetails, setIsUpdatingDetails] = useState(false);

    // Purchase Request Modal State
    const [isPurchaseModalOpen, setIsPurchaseModalOpen] = useState(false);
    const [purchaseItemId, setPurchaseItemId] = useState(''); 
    const [purchaseQty, setPurchaseQty] = useState('');
    const [purchaseCost, setPurchaseCost] = useState('');
    const [purchaseNotes, setPurchaseNotes] = useState('');

    // Confirm Receipt Logic
    const [isConfirmingReceipt, setIsConfirmingReceipt] = useState<string | null>(null);
    const [receivedInputs, setReceivedInputs] = useState<Record<string, string>>({});
    const [showSupplyHistory, setShowSupplyHistory] = useState(false);

    // Notifications State
    const [activeNotification, setActiveNotification] = useState<{title: string, message: string} | null>(null);

    // --- History Drawer State ---
    const [isHistoryDrawerOpen, setIsHistoryDrawerOpen] = useState(false);
    const [historyLogs, setHistoryLogs] = useState<any[]>([]);
    const [historyMaterial, setHistoryMaterial] = useState<FirestoreResource | null>(null);
    const [loadingHistory, setLoadingHistory] = useState(false);

    // --- Helpers ---
    const getResourceColName = (vid: VillageType) => vid === VillageType.A ? 'resourcesA' : 'resourcesB';
    const getInventoryColName = (vid: VillageType) => vid === VillageType.A ? 'inventoryA' : 'inventoryB';
    const getHarvestColName = (vid: VillageType) => vid === VillageType.A ? 'harvestYield_A' : 'harvestYield_B';
    
    // Updated Helper: Returns both Main and Expense collections
    const getFinancialCollections = (vid: VillageType) => {
        let suffix = 'A';
        if (vid === VillageType.B) suffix = 'B';
        return {
            main: `financialRecords_${suffix}`,
            expense: `expenses_${suffix}`
        };
    };

    const handleViewHistory = async (item: FirestoreResource) => {
        setHistoryMaterial(item);
        setIsHistoryDrawerOpen(true);
        setLoadingHistory(true);
        setHistoryLogs([]);
        try {
            const colName = getResourceColName(villageId);
            const q = query(
                collection(db, colName, item.id, "stock_history"),
                orderBy("timestamp", "desc"),
                limit(50) // Increased limit to see more history
            );
            const snap = await getDocs(q);
            const logs = snap.docs.map(d => ({id: d.id, ...d.data()}));
            setHistoryLogs(logs);
        } catch(e) {
            console.error("Error fetching history", e);
        } finally {
            setLoadingHistory(false);
        }
    };

    // --- Auto Set Thresholds Logic ---
    const handleAutoSetThresholds = async () => {
        const TARGET_YIELD_KG = 30;
        const collectionName = getResourceColName(villageId);
        let updatedCount = 0;

        try {
            await Promise.all(resources.map(async (res) => {
                const reqPerKg = MATERIAL_REQUIREMENTS[res.id];
                if (reqPerKg !== undefined) {
                    const newThreshold = reqPerKg * TARGET_YIELD_KG;
                    if (res.lowStockThreshold < newThreshold) {
                        const resRef = doc(db, collectionName, res.id);
                        await updateDoc(resRef, {
                            lowStockThreshold: newThreshold,
                            updatedAt: new Date().toISOString()
                        });
                        updatedCount++;
                    }
                }
            }));
            
            if (updatedCount > 0) {
                if (onSuccess) onSuccess(`Safety limits updated for ${updatedCount} items (Target: 30kg yield).`);
            } else {
                if (onSuccess) onSuccess("Stock limits already compliant with 30kg yield capacity.");
            }
        } catch (e) {
            console.error("Auto-set thresholds failed", e);
            alert("Failed to update thresholds.");
        }
    };

    // --- Auto Purchase Trigger Effect ---
    useEffect(() => {
        if (initialPurchaseState?.active) {
            setIsPurchaseModalOpen(true);
            if (initialPurchaseState.itemId) {
                setPurchaseItemId(initialPurchaseState.itemId);
            }
            if (onResetPurchaseState) onResetPurchaseState();
        }
    }, [initialPurchaseState]);

    // --- Auto-cleanup Equipment Locations ---
    useEffect(() => {
        const cleanupEquipmentLocations = async () => {
            try {
                const farmingCol = villageId === VillageType.A ? 'dailyfarming_logA' : 'dailyfarming_logB';
                const q = query(collection(db, farmingCol), orderBy('timestamp', 'desc'), limit(100));
                const snap = await getDocs(q);
                
                const activeRoomSet = new Set<string>();
                snap.forEach(doc => {
                    const data = doc.data();
                    if (data.type === 'SUBSTRATE_PREP' && data.batchStatus !== 'COMPLETED') {
                        const predicted = data.predictedYield || 0;
                        const actual = data.totalYield || 0;
                        const wastage = data.totalWastage || 0;
                        if (predicted > 0 && (actual + wastage) < predicted) {
                            if (data.roomId) activeRoomSet.add(data.roomId);
                        }
                    }
                });

                const equipment = resources.filter(r => r.category === 'Equipment');
                
                equipment.forEach(async (eq) => {
                    if (!eq.location) return;
                    const currentLocs = eq.location.split(',').map(s => s.trim()).filter(Boolean);
                    const validLocs = currentLocs.filter(loc => activeRoomSet.has(loc));
                    
                    if (validLocs.length !== currentLocs.length) {
                        const newLocStr = validLocs.join(', ');
                        const newStatus = validLocs.length > 0 ? 'Active' : 'Idle';
                        const resColName = villageId === VillageType.A ? 'resourcesA' : 'resourcesB';
                        
                        await updateDoc(doc(db, resColName, eq.id), {
                            location: newLocStr,
                            operationStatus: newStatus,
                            updatedAt: new Date().toISOString()
                        });
                        console.log(`Auto-removed inactive rooms from ${eq.name}`);
                    }
                });
            } catch (err) {
                console.error("Cleanup failed", err);
            }
        };

        if (resources.length > 0) {
            cleanupEquipmentLocations();
        }
    }, [villageId, resources]); 

    // --- Purchase Calculation Logic ---
    const selectedPurchaseResource = useMemo(() => 
        resources.find(r => r.id === purchaseItemId), 
    [purchaseItemId, resources]);

    useEffect(() => {
        if (selectedPurchaseResource && purchaseQty) {
            const qty = parseFloat(purchaseQty);
            if (!isNaN(qty) && qty > 0) {
                const factor = selectedPurchaseResource.unit === 'L' ? 10 : 1;
                const estimatedTotal = ((qty / factor) * (selectedPurchaseResource.unitCost || 0)).toFixed(2);
                setPurchaseCost(estimatedTotal);
            } else if (purchaseQty === '') {
                setPurchaseCost('');
            }
        }
    }, [selectedPurchaseResource, purchaseQty]);

    // Track pending deliveries from financial records
    const pendingReceipts = useMemo(() => {
        return financialRecords.filter(rec => 
            rec.category === 'Supplies' && 
            rec.type === 'EXPENSE' && 
            rec.status === 'COMPLETED' && 
            rec.receivedInStock === false &&
            rec.materialId // Must have a linked material
        );
    }, [financialRecords]);

    // History of received supplies
    const receivedSuppliesHistory = useMemo(() => {
        return financialRecords.filter(rec => 
            rec.category === 'Supplies' && 
            rec.type === 'EXPENSE' && 
            rec.receivedInStock === true &&
            rec.materialId
        ).sort((a,b) => (b.updatedAt || b.date).localeCompare(a.updatedAt || a.date)).slice(0, 10);
    }, [financialRecords]);

    // Map pending weights to resource ID for the "Pending Received" column
    const pendingWeightsByResource = useMemo(() => {
        const mapping: Record<string, number> = {};
        pendingReceipts.forEach(rec => {
            if (rec.materialId) {
                // Use orderQty if available, else extract from description
                const qty = rec.orderQty || (() => {
                    const match = rec.description?.match(/Purchase Request: ([\d.]+) /);
                    return match ? parseFloat(match[1]) : 0;
                })();
                mapping[rec.materialId] = (mapping[rec.materialId] || 0) + qty;
            }
        });
        return mapping;
    }, [pendingReceipts]);

    const totalResourceValue = useMemo(() => {
        return resources.reduce((acc, curr) => {
            const factor = curr.unit === 'L' ? 10 : 1;
            return acc + ((curr.quantity || 0) / factor * (curr.unitCost || 0));
        }, 0);
    }, [resources]);

    const resourceAtRisk = useMemo(() => {
        return resources.reduce((acc, curr) => {
            if (curr.quantity <= curr.lowStockThreshold) {
                const factor = curr.unit === 'L' ? 10 : 1;
                return acc + ((curr.quantity || 0) / factor * (curr.unitCost || 0));
            }
            return acc;
        }, 0);
    }, [resources]);

    // --- Data Fetching ---
    useEffect(() => {
        const resCol = collection(db, getResourceColName(villageId));
        const invCol = collection(db, getInventoryColName(villageId));

        const unsubRes = onSnapshot(resCol, (snapshot) => {
            const list: FirestoreResource[] = [];
            snapshot.forEach(doc => list.push({ id: doc.id, ...doc.data() } as FirestoreResource));
            
            // Check if equipment needs seeding (auto-generate requirement)
            const hasEquipment = list.some(i => i.category === 'Equipment');
            if (!hasEquipment && list.length > 0) {
                seedDefaultResources(list);
            } else if (list.length === 0) {
                seedDefaultResources([]);
            } else {
                setResources(list);
            }
            setLoading(false);
        });

        const unsubInv = onSnapshot(invCol, (snapshot) => {
             const list: InventoryItem[] = [];
             snapshot.forEach(doc => list.push({ id: doc.id, ...doc.data() } as InventoryItem));
             setInventory(list);
        });

        const harvCol = collection(db, getHarvestColName(villageId));
        const qHarvest = query(harvCol, orderBy('timestamp', 'desc'), limit(150));
        const unsubHarvest = onSnapshot(qHarvest, (snapshot) => {
            const list: HarvestLog[] = [];
            snapshot.forEach(doc => list.push({ id: doc.id, ...doc.data() } as HarvestLog));
            setHarvestLogs(list);
        });

        // Fetch Environment snapshot for Equipment Status
        const envColName = `environmentLogs_${villageId.replace(/\s/g, '')}`;
        const qEnv = query(collection(db, envColName), orderBy('timestamp', 'desc'), limit(1));
        const unsubEnv = onSnapshot(qEnv, (snap) => {
            if (!snap.empty) {
                const d = snap.docs[0].data();
                setLatestEnvLog({ temperature: d.temperature, humidity: d.humidity });
            }
        });

        return () => { unsubRes(); unsubInv(); unsubHarvest(); unsubEnv(); };
    }, [villageId]);

    const seedDefaultResources = async (existingList: FirestoreResource[] = []) => {
        const materialDefaults = [
            { name: "Straw (Substrate)", quantity: 1000, unit: "kg", category: "Input", lowStockThreshold: 200, unitCost: 1.50, materialId: "MAT-573260995" },
            { name: "Spawn (Inoculum)", quantity: 100, unit: "kg", category: "Input", lowStockThreshold: 20, unitCost: 12.00, materialId: "MAT-282015830" },
            { name: "Bran", quantity: 400, unit: "kg", category: "Nutrient", lowStockThreshold: 100, unitCost: 3.50, materialId: "MAT-406637503" },
            { name: "Gypsum (Conditioner)", quantity: 50, unit: "kg", category: "Nutrient", lowStockThreshold: 10, unitCost: 2.00, materialId: "MAT-446059102" },
            { name: "Water Supply Tank", quantity: 5000, unit: "L", category: "Utility", lowStockThreshold: 1000, unitCost: 0.50, materialId: "MAT-545594408" },
        ];

        const equipmentDefaults = [
            { name: "Exhaust Fan", quantity: 4, unit: "units", category: "Equipment", lowStockThreshold: 1, unitCost: 350.00, materialId: "EQP-FAN-001", location: "", condition: "Good" },
            { name: "Humidifier", quantity: 2, unit: "units", category: "Equipment", lowStockThreshold: 1, unitCost: 800.00, materialId: "EQP-HUM-001", location: "", condition: "Excellent" },
            { name: "Heater", quantity: 3, unit: "units", category: "Equipment", lowStockThreshold: 1, unitCost: 120.00, materialId: "EQP-HEAT-001", location: "", condition: "Fair" },
            { name: "Air Cooler", quantity: 1, unit: "system", category: "Equipment", lowStockThreshold: 0, unitCost: 1500.00, materialId: "EQP-COOL-001", location: "", condition: "Good" },
        ];

        const defaults = [...materialDefaults, ...equipmentDefaults];
        const col = collection(db, getResourceColName(villageId));
        
        for (const item of defaults) {
            if (!existingList.some(r => r.name === item.name)) {
                await setDoc(doc(col, item.materialId), { ...item, updatedAt: new Date().toISOString() });
            }
        }
    };

    const handleTransaction = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!selectedItem || !transQty) return;
        const qty = parseFloat(transQty);
        if (isNaN(qty) || qty <= 0) return;
        
        const collectionName = getResourceColName(villageId);
        const itemRef = doc(db, collectionName, selectedItem.id);
        
        const adjustment = transType === 'IN' ? qty : -qty;
        const newQuantity = (selectedItem.quantity || 0) + adjustment;

        if (transType === 'OUT' && newQuantity < 0) {
            alert("Insufficient stock!");
            return;
        }

        try {
            await updateDoc(itemRef, {
                quantity: newQuantity,
                updatedAt: new Date().toISOString()
            });

            await addDoc(collection(db, collectionName, selectedItem.id, "stock_history"), {
                type: transType, 
                quantity: qty,
                reason: transReason || (transType === 'IN' ? 'Restock' : 'Usage'),
                user: userEmail,
                timestamp: new Date().toISOString()
            });

            setIsTransModalOpen(false);
            setTransQty('');
            setTransReason('');
            setSelectedItem(null);
            if (onSuccess) onSuccess(`Stock ${transType === 'IN' ? 'added' : 'deducted'} successfully.`);
        } catch (e) {
            console.error("Transaction failed", e);
            alert("Failed to update stock.");
        }
    };
    
    const handleAddMaterial = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!newMatName || !newMatQty) return;
        try {
            const collectionName = getResourceColName(villageId);
            const initialQty = parseFloat(newMatQty) || 0;
            const threshold = parseFloat(newMatThreshold) || 0;
            const unitCost = parseFloat(newMatUnitCost) || 0;
            const materialId = "MAT-" + Date.now().toString().slice(-6) + Math.floor(100 + Math.random() * 900);
            await setDoc(doc(db, collectionName, materialId), {
                materialId,
                name: newMatName,
                category: newMatCategory,
                unit: newMatUnit,
                quantity: initialQty,
                lowStockThreshold: threshold,
                unitCost: unitCost,
                condition: 'N/A',
                updatedAt: new Date().toISOString()
            });
            if (initialQty > 0) {
                await addDoc(collection(db, collectionName, materialId, "stock_history"), {
                    type: 'IN', quantity: initialQty, reason: 'Initial Stock', user: userEmail, timestamp: new Date().toISOString()
                });
            }
            if (onSuccess) onSuccess(`Added ${newMatName} (ID: ${materialId})`);
            setIsAddMatModalOpen(false);
            setNewMatName(''); setNewMatCategory('Input'); setNewMatUnit('kg'); setNewMatQty(''); setNewMatThreshold(''); setNewMatUnitCost('');
        } catch (e) {
            console.error("Add Material failed", e);
            alert("Failed to add material.");
        }
    };

    const handleUpdateDetails = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!editItemId || !editItemUnitCost) return;
        setIsUpdatingDetails(true);
        try {
            const collectionName = getResourceColName(villageId);
            const itemRef = doc(db, collectionName, editItemId);
            await updateDoc(itemRef, {
                unitCost: parseFloat(editItemUnitCost),
                category: editItemCategory,
                unit: editItemUnit,
                updatedAt: new Date().toISOString()
            });
            if(onSuccess) onSuccess(`Updated ${editItemName} details.`);
            setIsEditMatModalOpen(false);
        } catch (e) {
            console.error("Update details failed", e);
            alert("Failed to update details.");
        } finally {
            setIsUpdatingDetails(false);
        }
    };

    const handlePurchaseRequest = async (e: React.FormEvent) => {
        e.preventDefault();
        const selectedResource = resources.find(r => r.id === purchaseItemId);
        if (!selectedResource) return;
        try {
            const { main, expense } = getFinancialCollections(villageId);
            const transactionId = "TXN-" + Date.now().toString().slice(-6) + Math.floor(100 + Math.random() * 900);
            const totalCost = parseFloat(purchaseCost) || 0;
            const qty = parseFloat(purchaseQty) || 1;
            const factor = selectedResource.unit === 'L' ? 10 : 1;
            const calcUnitCost = totalCost / (qty / factor);

            const recordData = {
                type: 'EXPENSE',
                status: 'PENDING',
                category: 'Supplies', 
                amount: totalCost,
                date: new Date().toISOString().split('T')[0],
                description: `Purchase Request: ${purchaseQty} ${selectedResource.unit} of ${selectedResource.name} (${selectedResource.materialId || 'No ID'}). Est Unit Cost: RM${calcUnitCost.toFixed(2)} per ${selectedResource.unit === 'L' ? '10L' : selectedResource.unit}. Notes: ${purchaseNotes}`,
                recordedBy: userEmail,
                villageId: villageId,
                transactionId,
                materialId: selectedResource.id, // Linked Material ID for tracking
                orderQty: qty,
                receivedInStock: false,
                createdAt: new Date().toISOString()
            };

            // DUAL WRITE: Write to specific expenses collection AND main financialRecords collection
            await setDoc(doc(db, expense, transactionId), recordData);
            await setDoc(doc(db, main, transactionId), recordData);

            setActiveNotification({
                title: "Purchase Request Sent",
                message: `Request for ${selectedResource.name} (Ref: ${transactionId}) has been sent to Finance.`
            });
            setIsPurchaseModalOpen(false);
            setPurchaseItemId(''); setPurchaseQty(''); setPurchaseCost(''); setPurchaseNotes('');
        } catch (e) {
            console.error("Purchase request failed", e);
            alert("Failed to send request.");
        }
    };

    const handleConfirmReceipt = async (rec: FinancialRecord) => {
        if (!rec.materialId) return;
        setIsConfirmingReceipt(rec.id);
        
        try {
            const inputVal = receivedInputs[rec.id];
            const orderQty = rec.orderQty || (() => {
                const match = rec.description?.match(/Purchase Request: ([\d.]+) /);
                return match ? parseFloat(match[1]) : 0;
            })();
            
            const actualQty = inputVal ? parseFloat(inputVal) : orderQty;
            
            if (isNaN(actualQty) || actualQty < 0) throw new Error("Please enter a valid received quantity.");

            const resColName = getResourceColName(villageId);
            const itemRef = doc(db, resColName, rec.materialId);
            
            const { main, expense } = getFinancialCollections(villageId);
            const mainFinRef = doc(db, main, rec.id);
            const expFinRef = doc(db, expense, rec.id);

            await updateDoc(itemRef, {
                quantity: increment(actualQty),
                updatedAt: new Date().toISOString()
            });

            await addDoc(collection(db, resColName, rec.materialId, "stock_history"), {
                type: 'IN', 
                quantity: actualQty,
                reason: `Supply Delivery Confirmed (Ref: ${rec.transactionId}) ${actualQty !== orderQty ? `[DISCREPANCY: Ordered ${orderQty}]` : ''}`,
                user: userEmail,
                timestamp: new Date().toISOString()
            });

            const updateData: any = {
                receivedInStock: true,
                orderQty: orderQty, 
                actualReceivedQty: actualQty,
                updatedAt: new Date().toISOString(),
                varianceResolved: actualQty === orderQty 
            };

            // DUAL UPDATE: Update both specific expense collection AND main collection
            await updateDoc(mainFinRef, updateData);
            
            try {
                await updateDoc(expFinRef, updateData);
            } catch (err) {
                console.warn("Could not update split expense collection (legacy record?):", err);
            }

            // --- AUTOMATIC REFUND GENERATION FOR SHORTAGES (Village A & B) ---
            if (actualQty < orderQty && (villageId === VillageType.A || villageId === VillageType.B)) {
                const shortage = orderQty - actualQty;
                // Calculate refund value based on original cost per unit
                const unitPrice = orderQty > 0 ? (rec.amount / orderQty) : 0;
                const refundValue = parseFloat((shortage * unitPrice).toFixed(2));

                if (refundValue > 0) {
                    const refundId = `TXN-REF-${Date.now().toString().slice(-6)}`;
                    const suffix = villageId === VillageType.A ? 'A' : 'B';
                    const incomeCol = `income_${suffix}`;
                    const mainCol = `financialRecords_${suffix}`;
                    
                    const refundRecord = {
                        transactionId: refundId,
                        type: 'INCOME',
                        category: 'Others', // Classified as 'Others' or could be 'Refund' if system allows
                        amount: refundValue,
                        date: new Date().toISOString().split('T')[0],
                        description: `Auto-Refund: Shortage of ${shortage} units from Txn ${rec.transactionId}`,
                        recordedBy: 'System/Automation',
                        villageId: villageId,
                        status: 'PENDING', // Mark as Pending for review
                        relatedTransactionId: rec.transactionId,
                        createdAt: new Date().toISOString()
                    };

                    // Write Refund to Income & Main Ledger
                    await setDoc(doc(db, incomeCol, refundId), refundRecord);
                    await setDoc(doc(db, mainCol, refundId), refundRecord);
                    
                    if (onSuccess) onSuccess(`Refund (Pending) of RM${refundValue} generated for shortage.`);
                }
            }
            // -----------------------------------------------------------------

            if (onSuccess) onSuccess(`Stock updated: +${actualQty} received for supply ${rec.transactionId}`);
            
            const newInputs = { ...receivedInputs };
            delete newInputs[rec.id];
            setReceivedInputs(newInputs);

        } catch (e: any) {
            console.error("Confirmation failed", e);
            alert("Error confirming receipt: " + e.message);
        } finally {
            setIsConfirmingReceipt(null);
        }
    };

    const materialList = resources.filter(r => r.category !== 'Equipment');
    const equipmentList = resources.filter(r => r.category === 'Equipment');

    return (
        <div className="space-y-6 animate-fade-in-up relative">
            {/* History Drawer */}
            {isHistoryDrawerOpen && historyMaterial && (
                <div className="fixed inset-0 z-[70] overflow-hidden">
                    <div className="absolute inset-0 bg-gray-500 bg-opacity-75 transition-opacity" onClick={() => setIsHistoryDrawerOpen(false)}></div>
                    <div className="fixed inset-y-0 right-0 pl-10 max-w-full flex">
                        <div className="w-screen max-w-md animate-slide-in-right">
                            <div className="h-full flex flex-col bg-white shadow-xl overflow-y-scroll">
                                <div className="py-6 px-4 bg-indigo-700 sm:px-6">
                                    <div className="flex items-center justify-between">
                                        <h2 className="text-lg font-medium text-white" id="slide-over-title">
                                            {historyMaterial.name} History
                                        </h2>
                                        <div className="ml-3 h-7 flex items-center">
                                            <button type="button" className="bg-indigo-700 rounded-md text-indigo-200 hover:text-white focus:outline-none" onClick={() => setIsHistoryDrawerOpen(false)}>
                                                <span className="sr-only">Close panel</span>
                                                <svg className="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                                                </svg>
                                            </button>
                                        </div>
                                    </div>
                                    <div className="mt-1">
                                        <p className="text-sm text-indigo-300">
                                            Stock ID: {historyMaterial.materialId || historyMaterial.id}
                                        </p>
                                    </div>
                                </div>
                                <div className="relative flex-1 py-6 px-4 sm:px-6">
                                    {loadingHistory ? (
                                        <div className="flex justify-center mt-10"><div className="animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-600"></div></div>
                                    ) : (
                                        <div className="flow-root">
                                            <ul className="-mb-8">
                                                {historyLogs.length === 0 ? (
                                                    <li className="text-center text-gray-500 text-sm italic">No history found.</li>
                                                ) : (
                                                    historyLogs.map((log, logIdx) => (
                                                        <li key={log.id}>
                                                            <div className="relative pb-8">
                                                                {logIdx !== historyLogs.length - 1 ? (
                                                                    <span className="absolute top-4 left-4 -ml-px h-full w-0.5 bg-gray-200" aria-hidden="true"></span>
                                                                ) : null}
                                                                <div className="relative flex space-x-3">
                                                                    <div>
                                                                        <span className={`h-8 w-8 rounded-full flex items-center justify-center ring-8 ring-white ${log.type === 'IN' ? 'bg-green-500' : 'bg-red-500'}`}>
                                                                            {log.type === 'IN' ? (
                                                                                <svg className="h-5 w-5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6v6m0 0v6m0-6h6m-6 0H6" /></svg>
                                                                            ) : (
                                                                                <svg className="h-5 w-5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20 12H4" /></svg>
                                                                            )}
                                                                        </span>
                                                                    </div>
                                                                    <div className="min-w-0 flex-1 pt-1.5 flex justify-between space-x-4">
                                                                        <div>
                                                                            <p className="text-sm text-gray-500">
                                                                                {log.type === 'IN' ? 'Added' : 'Deducted'} <span className="font-medium text-gray-900">{log.quantity} {historyMaterial.unit}</span>
                                                                            </p>
                                                                            <p className="text-xs text-gray-400 mt-0.5">{log.reason}</p>
                                                                        </div>
                                                                        <div className="text-right text-sm whitespace-nowrap text-gray-500">
                                                                            <time dateTime={log.timestamp}>{new Date(log.timestamp).toLocaleDateString()}</time>
                                                                            <div className="text-[10px] text-gray-400">{new Date(log.timestamp).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})}</div>
                                                                            <div className="text-[10px] font-medium text-indigo-600 mt-1">{log.user ? log.user.split('@')[0] : 'System'}</div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </li>
                                                    ))
                                                )}
                                            </ul>
                                        </div>
                                    )}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            )}

            {/* Notification Toast */}
            {activeNotification && (
                <div className="fixed bottom-6 right-6 z-[60] max-w-sm w-full bg-white border-l-4 border-indigo-600 shadow-2xl rounded-r-lg pointer-events-auto transform transition-all duration-300 ease-in-out translate-y-0 opacity-100">
                    <div className="p-4">
                        <div className="flex items-start">
                            <div className="flex-shrink-0">
                                <svg className="h-6 w-6 text-indigo-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                                </svg>
                            </div>
                            <div className="ml-3 w-0 flex-1 pt-0.5">
                                <p className="text-sm font-bold text-gray-900">{activeNotification.title}</p>
                                <p className="mt-1 text-sm text-gray-500">{activeNotification.message}</p>
                                <div className="mt-4 flex">
                                    <button onClick={() => setActiveNotification(null)} className="inline-flex items-center px-3 py-1.5 border border-transparent text-xs font-medium rounded-md text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">Mark as Read</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            )}

            {/* KPI Section */}
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm relative overflow-hidden border-l-4 border-l-indigo-500">
                    <div className="relative z-10">
                        <h3 className="text-[10px] font-black text-indigo-500 uppercase tracking-widest mb-1">Inventory Assets</h3>
                        <div className="flex items-baseline gap-1">
                            <span className="text-sm font-bold text-gray-400">RM</span>
                            <span className="text-3xl font-black text-indigo-700">{(totalResourceValue || 0).toLocaleString(undefined, {minimumFractionDigits: 2})}</span>
                        </div>
                        {resourceAtRisk > 0 && (
                            <p className="text-[10px] text-red-600 font-black uppercase mt-1 flex items-center gap-1">
                                <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
                                RM{resourceAtRisk.toLocaleString()} at risk (low stock)
                            </p>
                        )}
                    </div>
                </div>
            </div>

            {/* Pending Receipts Logic */}
            {pendingReceipts.length > 0 && (
                <div className="bg-orange-50 rounded-xl border border-orange-100 overflow-hidden animate-fade-in shadow-sm">
                    <div className="px-6 py-4 border-b border-orange-200 bg-orange-100/50 flex justify-between items-center">
                        <div>
                            <h3 className="text-sm font-black text-orange-900 uppercase tracking-tight flex items-center gap-2">
                                <span className="relative flex h-3 w-3">
                                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-orange-400 opacity-75"></span>
                                  <span className="relative inline-flex rounded-full h-3 w-3 bg-orange-500"></span>
                                </span>
                                Action Required: Confirm Receipts
                            </h3>
                            <p className="text-[10px] text-orange-700 font-bold uppercase mt-1">Supplies paid for but not yet marked as 'In Stock'</p>
                        </div>
                        <span className="bg-orange-200 text-orange-800 text-xs font-bold px-3 py-1 rounded-full">{pendingReceipts.length} Pending</span>
                    </div>
                    <div className="overflow-x-auto">
                        <table className="min-w-full divide-y divide-orange-100">
                            <thead className="bg-orange-50/50">
                                <tr className="text-[9px] font-black text-orange-600 uppercase tracking-widest">
                                    <th className="px-6 py-3 text-left">Ref ID</th>
                                    <th className="px-6 py-3 text-left">Material Name</th>
                                    <th className="px-6 py-3 text-right">Order Qty</th>
                                    <th className="px-6 py-3 text-center">Actual Received Qty</th>
                                    <th className="px-6 py-3 text-left">Payment Date</th>
                                    <th className="px-6 py-3 text-center">Action</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-orange-100">
                                {pendingReceipts.map(rec => {
                                    const resource = resources.find(r => r.id === rec.materialId);
                                    const orderQty = rec.orderQty || 0;
                                    const currentInput = receivedInputs[rec.id];
                                    const actualQty = currentInput ? parseFloat(currentInput) : orderQty;
                                    const hasDiscrepancy = actualQty !== orderQty;

                                    return (
                                        <tr key={rec.id} className="hover:bg-orange-100/30 transition-colors">
                                            <td className="px-6 py-4 whitespace-nowrap text-[10px] font-mono font-bold text-orange-900">{rec.transactionId}</td>
                                            <td className="px-6 py-4 whitespace-nowrap text-xs font-bold text-gray-700">
                                                {resource?.name || 'Unknown Material'}
                                                <div className="text-[9px] text-gray-400 font-normal uppercase">{rec.materialId}</div>
                                            </td>
                                            <td className="px-6 py-4 whitespace-nowrap text-sm font-black text-right text-gray-400">
                                                {orderQty} <span className="text-[9px] font-bold">{resource?.unit || ''}</span>
                                            </td>
                                            <td className="px-6 py-4 whitespace-nowrap text-center">
                                                <div className="inline-flex items-center gap-2">
                                                    <input 
                                                        type="number" 
                                                        step="any"
                                                        value={currentInput ?? orderQty}
                                                        onChange={(e) => setReceivedInputs({...receivedInputs, [rec.id]: e.target.value})}
                                                        className={`w-24 p-1.5 border rounded-lg text-xs font-black text-center focus:ring-2 focus:ring-orange-500 transition-all ${hasDiscrepancy ? 'border-red-400 bg-red-50 text-red-700' : 'border-gray-200 bg-white text-gray-700'}`}
                                                    />
                                                </div>
                                            </td>
                                            <td className="px-6 py-4 whitespace-nowrap text-[10px] font-bold text-gray-500 uppercase">{rec.settledDate || rec.date}</td>
                                            <td className="px-6 py-4 whitespace-nowrap text-center">
                                                <button 
                                                    onClick={() => handleConfirmReceipt(rec)}
                                                    disabled={isConfirmingReceipt === rec.id}
                                                    className={`px-3 py-1.5 text-white text-[10px] font-black uppercase rounded-lg shadow-md transition-all flex items-center gap-2 mx-auto disabled:opacity-50 ${hasDiscrepancy ? 'bg-red-600 hover:bg-red-700' : 'bg-orange-600 hover:bg-orange-700'}`}
                                                >
                                                    {isConfirmingReceipt === rec.id ? 'Saving...' : hasDiscrepancy ? 'Confirm Partial' : 'Confirm Received'}
                                                </button>
                                            </td>
                                        </tr>
                                    );
                                })}
                            </tbody>
                        </table>
                    </div>
                </div>
            )}

            {/* Material Table and Action Buttons */}
            
            <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
                <div className="px-6 py-4 border-b border-gray-200 bg-gray-50 flex flex-col sm:flex-row justify-between items-start sm:items-center">
                    <div>
                        <h2 className="text-lg font-black text-gray-900 tracking-tight">Material Availability (Inputs)</h2>
                        <p className="text-xs text-gray-400 font-medium">Costing and quantity control for raw supplies.</p>
                    </div>
                    <div className="mt-2 sm:mt-0 flex gap-2 flex-wrap">
                        <button onClick={handleAutoSetThresholds} className="px-4 py-2.5 bg-orange-50 text-orange-600 border border-orange-200 text-xs font-black uppercase rounded-xl shadow-sm hover:bg-orange-100 transition-all flex items-center gap-2">
                            Enforce Safe Limits (30kg)
                        </button>
                        <button onClick={() => setShowSupplyHistory(!showSupplyHistory)} className="px-4 py-2.5 bg-white text-blue-600 border border-blue-200 text-xs font-black uppercase rounded-xl shadow-sm hover:bg-blue-50 transition-all flex items-center gap-2">
                            {showSupplyHistory ? 'Hide History' : 'Supply History'}
                        </button>
                        <button onClick={() => { setIsAddMatModalOpen(true); }} className="px-4 py-2.5 bg-white text-gray-700 border border-gray-200 text-xs font-black uppercase rounded-xl shadow-sm hover:bg-gray-50 transition-all flex items-center gap-2">
                            New Material
                        </button>
                        <button onClick={() => { setPurchaseItemId(''); setIsPurchaseModalOpen(true); }} className="px-4 py-2.5 bg-indigo-600 text-white hover:bg-indigo-700 text-xs font-black uppercase rounded-xl shadow-lg transition-all flex items-center gap-2">
                            Purchase
                        </button>
                    </div>
                </div>

                {showSupplyHistory && (
                    <div className="bg-slate-50 border-b border-gray-200 p-4 animate-fade-in">
                        <h4 className="text-xs font-bold text-gray-500 uppercase mb-3 ml-2">Recent Confirmed Arrivals</h4>
                        <div className="overflow-x-auto">
                            <table className="min-w-full divide-y divide-gray-200 text-xs bg-white rounded-lg border border-gray-200 shadow-sm">
                                <thead className="bg-gray-100">
                                    <tr><th className="px-4 py-2 text-left text-gray-500">Date Received</th><th className="px-4 py-2 text-left text-gray-500">Transaction ID</th><th className="px-4 py-2 text-left text-gray-500">Item</th><th className="px-4 py-2 text-right text-gray-500">Qty Received</th><th className="px-4 py-2 text-right text-gray-500">Cost</th></tr>
                                </thead>
                                <tbody className="divide-y divide-gray-100">
                                    {receivedSuppliesHistory.map(rec => {
                                        const res = resources.find(r => r.id === rec.materialId);
                                        return (
                                            <tr key={rec.id} className="hover:bg-gray-50">
                                                <td className="px-4 py-2 text-gray-500">{new Date(rec.updatedAt || rec.date).toLocaleDateString()}</td>
                                                <td className="px-4 py-2 font-mono">{rec.transactionId}</td>
                                                <td className="px-4 py-2 font-bold">{res?.name || 'Unknown'}</td>
                                                <td className="px-4 py-2 text-right text-green-600 font-bold">+{rec.actualReceivedQty || rec.orderQty} {res?.unit}</td>
                                                <td className="px-4 py-2 text-right">RM{rec.amount.toFixed(2)}</td>
                                            </tr>
                                        );
                                    })}
                                    {receivedSuppliesHistory.length === 0 && <tr><td colSpan={5} className="text-center py-4 text-gray-400 italic">No history available</td></tr>}
                                </tbody>
                            </table>
                        </div>
                    </div>
                )}

                <div className="overflow-x-auto">
                    <table className="min-w-full divide-y divide-gray-100">
                        <thead className="bg-gray-50/50">
                            <tr className="text-[10px] font-black text-gray-400 uppercase tracking-widest">
                                <th className="px-6 py-4 text-left">Item Details</th>
                                <th className="px-6 py-4 text-left">Category</th>
                                <th className="px-6 py-4 text-center">Unit</th>
                                <th className="px-6 py-4 text-right">Pending Received</th>
                                <th className="px-6 py-4 text-right">Quantity</th>
                                <th className="px-6 py-4 text-right">Unit Cost (RM)</th>
                                <th className="px-6 py-4 text-center">Availability</th>
                                <th className="px-6 py-4 text-center">Low Stock Limit</th>
                            </tr>
                        </thead>
                        <tbody className="bg-white divide-y divide-gray-100">
                            {loading ? (
                                <tr><td colSpan={8} className="px-6 py-12 text-center text-sm text-gray-400 italic">Loading resources...</td></tr>
                            ) : materialList.length === 0 ? (
                                <tr><td colSpan={8} className="px-6 py-12 text-center text-sm text-gray-400 italic">No resources tracked for {villageId} yet.</td></tr>
                            ) : (
                                materialList.map((item) => {
                                    const quantity = item.quantity || 0;
                                    const pending = pendingWeightsByResource[item.id] || 0;
                                    const unitCost = item.unitCost || 0;
                                    const isLow = quantity <= item.lowStockThreshold;
                                    const isCritical = quantity <= (item.lowStockThreshold * 0.2);
                                    return (
                                        <tr key={item.id} className="hover:bg-gray-50 transition-colors">
                                            <td className="px-6 py-5 whitespace-nowrap cursor-pointer group" onClick={() => handleViewHistory(item)}>
                                                <div className="text-sm font-black text-gray-900 group-hover:text-indigo-600 transition-colors flex items-center gap-2">
                                                    {item.name}
                                                    <svg className="w-4 h-4 text-gray-300 group-hover:text-indigo-400 opacity-0 group-hover:opacity-100 transition-all" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 00-2-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01" /></svg>
                                                </div>
                                                <div className="text-[10px] text-gray-400 font-bold uppercase tracking-tight">{item.materialId || item.id}</div>
                                            </td>
                                            <td className="px-6 py-5 whitespace-nowrap">
                                                <span className="px-2.5 py-1 rounded-lg text-[10px] font-black uppercase bg-gray-100 text-gray-500 border border-gray-200">{item.category}</span>
                                            </td>
                                            <td className="px-6 py-5 whitespace-nowrap text-center text-xs font-bold text-gray-700">
                                                {item.unit}
                                            </td>
                                            <td className="px-6 py-5 whitespace-nowrap text-sm font-bold text-right text-orange-600">
                                                {pending > 0 ? `+${pending.toLocaleString()}` : '-'}
                                            </td>
                                            <td className="px-6 py-5 whitespace-nowrap text-sm font-black text-right text-gray-900">
                                                {quantity.toLocaleString()} 
                                            </td>
                                            <td className="px-6 py-5 whitespace-nowrap text-sm font-bold text-right text-gray-500">
                                                {unitCost.toFixed(2)}
                                            </td>
                                            <td className="px-6 py-5 whitespace-nowrap text-center">
                                                {isCritical ? (
                                                    <span className="px-3 py-1 text-[10px] font-black uppercase rounded-full bg-red-100 text-red-700 border border-red-200 animate-pulse">Critical</span>
                                                ) : isLow ? (
                                                    <span className="px-3 py-1 text-[10px] font-black uppercase rounded-full bg-yellow-100 text-yellow-800 border border-yellow-200">Low Stock</span>
                                                ) : (
                                                    <span className="px-3 py-1 text-[10px] font-black uppercase rounded-full bg-green-100 text-green-800 border border-green-200">OK</span>
                                                )}
                                            </td>
                                            <td className="px-6 py-5 whitespace-nowrap text-center text-xs font-bold text-gray-500">
                                                {item.lowStockThreshold}
                                            </td>
                                        </tr>
                                    );
                                })
                            )}
                        </tbody>
                    </table>
                </div>
            </div>

            {/* Equipment Table */}
            <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden mt-6">
                <div className="px-6 py-4 border-b border-gray-200 bg-gray-50 flex justify-between items-center">
                    <div>
                        <h2 className="text-lg font-black text-gray-900 tracking-tight">Facility Equipment & Hardware</h2>
                        <p className="text-xs text-gray-400 font-medium">Active environmental control systems.</p>
                    </div>
                    <div className="text-[10px] font-bold uppercase text-gray-400 bg-gray-100 px-3 py-1 rounded-full">
                        System Status: {latestEnvLog ? `Monitoring (${latestEnvLog.temperature}°C / ${latestEnvLog.humidity}%)` : 'Syncing...'}
                    </div>
                </div>
                <div className="overflow-x-auto">
                    <table className="min-w-full divide-y divide-gray-100">
                        <thead className="bg-gray-50/50">
                            <tr className="text-[10px] font-black text-gray-400 uppercase tracking-widest">
                                <th className="px-6 py-4 text-left">Equipment Name</th>
                                <th className="px-6 py-4 text-left">Location (Linked)</th>
                                <th className="px-6 py-4 text-left">Condition</th>
                                <th className="px-6 py-4 text-center">Unit</th>
                                <th className="px-6 py-4 text-right">Quantity</th>
                                <th className="px-6 py-4 text-right">Unit Cost (RM)</th>
                                <th className="px-6 py-4 text-center">Availability</th>
                            </tr>
                        </thead>
                        <tbody className="bg-white divide-y divide-gray-100">
                            {equipmentList.length === 0 ? (
                                <tr><td colSpan={7} className="px-6 py-12 text-center text-sm text-gray-400 italic">No equipment logged.</td></tr>
                            ) : (
                                equipmentList.map((item) => {
                                    // Availability Calculation
                                    const totalQty = item.quantity || 0;
                                    const locations = item.location ? item.location.split(',').map(s => s.trim()).filter(Boolean) : [];
                                    const inUseCount = locations.length;
                                    const availableCount = Math.max(0, totalQty - inUseCount);
                                    const isUnavailable = availableCount === 0;

                                    return (
                                        <tr key={item.id} className="hover:bg-gray-50 transition-colors">
                                            <td className="px-6 py-5 whitespace-nowrap">
                                                <div className="text-sm font-black text-gray-900">{item.name}</div>
                                                <div className="text-[10px] text-gray-400 font-bold uppercase tracking-tight">{item.materialId || item.id}</div>
                                            </td>
                                            <td className="px-6 py-5 whitespace-nowrap text-xs font-bold text-gray-600">
                                                {locations.length > 0 ? (
                                                    <div className="flex flex-wrap gap-1 max-w-[200px]">
                                                        {locations.map((loc, i) => (
                                                            <span key={i} className="px-2 py-0.5 bg-blue-50 text-blue-600 rounded border border-blue-100 uppercase text-[9px]">{loc}</span>
                                                        ))}
                                                    </div>
                                                ) : <span className="text-gray-400 italic">Storage</span>}
                                            </td>
                                            <td className="px-6 py-5 whitespace-nowrap text-xs font-bold">
                                                {item.condition || 'Unknown'}
                                            </td>
                                            <td className="px-6 py-5 whitespace-nowrap text-center text-xs font-bold text-gray-700">
                                                {item.unit}
                                            </td>
                                            <td className="px-6 py-5 whitespace-nowrap text-right text-sm font-black text-gray-900">
                                                {availableCount} <span className="text-gray-400 font-bold text-[10px]">/ {totalQty}</span>
                                            </td>
                                            <td className="px-6 py-5 whitespace-nowrap text-right text-sm font-bold text-gray-500">
                                                {item.unitCost ? item.unitCost.toFixed(2) : '0.00'}
                                            </td>
                                            <td className="px-6 py-5 whitespace-nowrap text-center">
                                                <span className={`px-2.5 py-1 rounded-full text-[10px] font-black uppercase ${isUnavailable ? 'bg-red-100 text-red-700' : 'bg-green-100 text-green-800'}`}>
                                                    {isUnavailable ? 'In Use' : 'Available'}
                                                </span>
                                            </td>
                                        </tr>
                                    );
                                })
                            )}
                        </tbody>
                    </table>
                </div>
            </div>

            {/* Modals */}
            {/* Purchase Request Modal */}
            {isPurchaseModalOpen && (
                <div className="fixed inset-0 bg-black/60 flex items-center justify-center z-[80] p-4 backdrop-blur-sm">
                    <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg overflow-hidden animate-scale-up">
                        <div className="p-6 bg-indigo-600 text-white flex justify-between items-center">
                            <h3 className="font-bold text-lg">Purchase Request</h3>
                            <button onClick={() => setIsPurchaseModalOpen(false)} className="text-white hover:text-white/80 font-bold text-2xl">×</button>
                        </div>
                        <form onSubmit={handlePurchaseRequest} className="p-6 space-y-4">
                            <div>
                                <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Select Item</label>
                                <select 
                                    value={purchaseItemId} 
                                    onChange={e => setPurchaseItemId(e.target.value)} 
                                    className="w-full p-2 border rounded-lg bg-gray-50 font-medium"
                                    required
                                >
                                    <option value="">Select Material...</option>
                                    {resources.map(r => <option key={r.id} value={r.id}>{r.name} ({r.unit})</option>)}
                                </select>
                            </div>
                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Quantity ({selectedPurchaseResource?.unit || 'Units'})</label>
                                    <input 
                                        type="number" 
                                        value={purchaseQty} 
                                        onChange={e => setPurchaseQty(e.target.value)} 
                                        className="w-full p-2 border rounded-lg" 
                                        required 
                                        min="0"
                                        step="0.01"
                                    />
                                </div>
                                <div>
                                    <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Total Est. Cost (RM)</label>
                                    <input 
                                        type="number" 
                                        value={purchaseCost} 
                                        onChange={e => setPurchaseCost(e.target.value)} 
                                        className="w-full p-2 border rounded-lg font-bold text-indigo-600" 
                                        required 
                                        min="0"
                                        step="0.01"
                                    />
                                </div>
                            </div>
                            <div>
                                <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Notes / Supplier Info</label>
                                <textarea 
                                    value={purchaseNotes} 
                                    onChange={e => setPurchaseNotes(e.target.value)} 
                                    className="w-full p-2 border rounded-lg h-20" 
                                    placeholder="Optional details for finance..." 
                                />
                            </div>
                            <div className="flex justify-end pt-2">
                                <button type="submit" className="w-full bg-indigo-600 text-white font-bold py-3 rounded-lg hover:bg-indigo-700 shadow-lg">Submit Request</button>
                            </div>
                        </form>
                    </div>
                </div>
            )}

            {/* Stock Adjustment Modal */}
            {isTransModalOpen && selectedItem && (
                <div className="fixed inset-0 bg-black/60 flex items-center justify-center z-[80] p-4 backdrop-blur-sm">
                    <div className="bg-white rounded-2xl shadow-2xl w-full max-w-sm overflow-hidden animate-scale-up">
                        <div className="p-6 border-b flex justify-between items-center bg-gray-50">
                            <div>
                                <h3 className="font-bold text-lg text-gray-900">Adjust Stock</h3>
                                <p className="text-xs text-gray-500 font-medium">{selectedItem.name}</p>
                            </div>
                            <button onClick={() => setIsTransModalOpen(false)} className="text-gray-400 hover:text-gray-600 font-bold text-xl">×</button>
                        </div>
                        <form onSubmit={handleTransaction} className="p-6 space-y-4">
                            <div className="flex bg-gray-100 p-1 rounded-lg">
                                <button type="button" onClick={()=>setTransType('IN')} className={`flex-1 py-2 rounded-md text-xs font-bold uppercase transition-all ${transType === 'IN' ? 'bg-white text-green-600 shadow-sm' : 'text-gray-400'}`}>Add Stock</button>
                                <button type="button" onClick={()=>setTransType('OUT')} className={`flex-1 py-2 rounded-md text-xs font-bold uppercase transition-all ${transType === 'OUT' ? 'bg-white text-red-600 shadow-sm' : 'text-gray-400'}`}>Deduct</button>
                            </div>
                            <div>
                                <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Quantity ({selectedItem.unit})</label>
                                <input type="number" step="0.01" value={transQty} onChange={e=>setTransQty(e.target.value)} className="w-full p-2 border rounded-lg text-lg font-bold" required autoFocus />
                            </div>
                            <div>
                                <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Reason</label>
                                <input type="text" value={transReason} onChange={e=>setTransReason(e.target.value)} className="w-full p-2 border rounded-lg" placeholder="e.g. Spoilage, Correction" />
                            </div>
                            <button type="submit" className={`w-full py-3 rounded-lg font-bold text-white shadow-lg ${transType === 'IN' ? 'bg-green-600 hover:bg-green-700' : 'bg-red-600 hover:bg-red-700'}`}>
                                Confirm {transType === 'IN' ? 'Addition' : 'Deduction'}
                            </button>
                        </form>
                    </div>
                </div>
            )}

            {/* Add Material Modal */}
            {isAddMatModalOpen && (
                <div className="fixed inset-0 bg-black/60 flex items-center justify-center z-[80] p-4 backdrop-blur-sm">
                    <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md overflow-hidden animate-scale-up">
                        <div className="p-6 bg-gray-900 text-white flex justify-between items-center">
                            <h3 className="font-bold text-lg">New Inventory Item</h3>
                            <button onClick={() => setIsAddMatModalOpen(false)} className="text-white hover:text-white/80 font-bold text-2xl">×</button>
                        </div>
                        <form onSubmit={handleAddMaterial} className="p-6 space-y-4">
                            <div className="grid grid-cols-2 gap-4">
                                <div><label className="block text-xs font-bold text-gray-500 uppercase mb-1">Name</label><input type="text" value={newMatName} onChange={e=>setNewMatName(e.target.value)} className="w-full p-2 border rounded-lg" required /></div>
                                <div><label className="block text-xs font-bold text-gray-500 uppercase mb-1">Category</label><select value={newMatCategory} onChange={e=>setNewMatCategory(e.target.value)} className="w-full p-2 border rounded-lg bg-white"><option value="Input">Input</option><option value="Nutrient">Nutrient</option><option value="Utility">Utility</option><option value="Equipment">Equipment</option></select></div>
                            </div>
                            <div className="grid grid-cols-2 gap-4">
                                <div><label className="block text-xs font-bold text-gray-500 uppercase mb-1">Initial Qty</label><input type="number" value={newMatQty} onChange={e=>setNewMatQty(e.target.value)} className="w-full p-2 border rounded-lg" required /></div>
                                <div><label className="block text-xs font-bold text-gray-500 uppercase mb-1">Unit</label><select value={newMatUnit} onChange={e=>setNewMatUnit(e.target.value)} className="w-full p-2 border rounded-lg bg-white"><option value="kg">kg</option><option value="L">L</option><option value="units">units</option><option value="packs">packs</option></select></div>
                            </div>
                            <div className="grid grid-cols-2 gap-4">
                                <div><label className="block text-xs font-bold text-gray-500 uppercase mb-1">Low Limit</label><input type="number" value={newMatThreshold} onChange={e=>setNewMatThreshold(e.target.value)} className="w-full p-2 border rounded-lg" required /></div>
                                <div><label className="block text-xs font-bold text-gray-500 uppercase mb-1">Est. Unit Cost</label><input type="number" step="0.01" value={newMatUnitCost} onChange={e=>setNewMatUnitCost(e.target.value)} className="w-full p-2 border rounded-lg" required /></div>
                            </div>
                            <button type="submit" className="w-full bg-gray-900 text-white font-bold py-3 rounded-lg hover:bg-black shadow-lg">Create Item</button>
                        </form>
                    </div>
                </div>
            )}

            {/* Edit Material Modal */}
            {isEditMatModalOpen && (
                <div className="fixed inset-0 bg-black/60 flex items-center justify-center z-[80] p-4 backdrop-blur-sm">
                    <div className="bg-white rounded-2xl shadow-2xl w-full max-w-sm overflow-hidden animate-scale-up">
                        <div className="p-6 border-b flex justify-between items-center">
                            <h3 className="font-bold text-lg text-gray-900">Edit Details</h3>
                            <button onClick={() => setIsEditMatModalOpen(false)} className="text-gray-400 hover:text-gray-600 font-bold text-xl">×</button>
                        </div>
                        <form onSubmit={handleUpdateDetails} className="p-6 space-y-4">
                            <div className="bg-gray-50 p-3 rounded-lg text-center">
                                <span className="block text-xs font-bold text-gray-400 uppercase">Editing</span>
                                <span className="font-bold text-lg text-indigo-600">{editItemName}</span>
                            </div>
                            <div>
                                <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Unit Cost (RM)</label>
                                <input type="number" step="0.01" value={editItemUnitCost} onChange={e=>setEditItemUnitCost(e.target.value)} className="w-full p-2 border rounded-lg" required />
                            </div>
                            <div className="grid grid-cols-2 gap-4">
                                <div><label className="block text-xs font-bold text-gray-500 uppercase mb-1">Category</label><select value={editItemCategory} onChange={e=>setEditItemCategory(e.target.value)} className="w-full p-2 border rounded-lg bg-white"><option value="Input">Input</option><option value="Nutrient">Nutrient</option><option value="Utility">Utility</option><option value="Equipment">Equipment</option></select></div>
                                <div><label className="block text-xs font-bold text-gray-500 uppercase mb-1">Unit</label><select value={editItemUnit} onChange={e=>setEditItemUnit(e.target.value)} className="w-full p-2 border rounded-lg bg-white"><option value="kg">kg</option><option value="L">L</option><option value="units">units</option><option value="packs">packs</option></select></div>
                            </div>
                            <button type="submit" disabled={isUpdatingDetails} className="w-full bg-blue-600 text-white font-bold py-3 rounded-lg hover:bg-blue-700 shadow-lg disabled:opacity-50">
                                {isUpdatingDetails ? 'Saving...' : 'Update Details'}
                            </button>
                        </form>
                    </div>
                </div>
            )}
        </div>
    );
};